### PR TITLE
don't show distance circle for waypoints of archived caches

### LINKED ISSUE #13117: Archived mystery with modified coords still shows 161m circle
### Describe your problem!

Reported by a user on support:
While the new feature, that archived caches do no longer have the 161 meter circle, works in general, there seem be cases, where its not working.

In the attached example pictures, there is one archived traditional without circle, but on lower right one archived mystery with modified coords which still shows a circle.

### How to reproduce?

Screenshot_20220609-223000

(Side note when looking at the picture: The user has modified the appearance of the circles, which caused me at first sight not to see the problem, but its there).

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Unclear

### c:geo Version

2022.06.06

### System information

```text
## System information

c:geo version: 2022.06.06

Device:
-------
- Device type: Power Armor 13 (Power_Armor_13_EEA, Ulefone)
- Available processors: 8
- Android version: 11
- Android build: S7S68B7.GQU.Ulefone_EEA.HB.HJ.AZVKPVFMXPE.20210720.V3.02
- Screen resolution: 1080x2254px (360x748dp)
- Pixel density: 2.5500002
- System font scale: 0.85 / used scale: 0.85
- Sailfish OS detected: false
- Google Play services: enabled - 22.15.14 (150408-441847897)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:185
- Set language: cs_CZ (system default)
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Last backup: never
- Routing mode: Car
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Map: Czech_republic_gccz (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:Documents/Cgeo/maps/czech_republic_gccz.map
- Atts: Tourist map for Locus, c:geo, a:drake, OruxMaps and other applications using Mapsforge library, OpenStreetMap data and SRTM data. Data from 2022-03-12. By Speirs http://osm.paws.cz
  - Theme: paws_S.zip:paws_S/paws_S.xml

Filters:
-------
- Hide waypoints: original visited
- LIVE: Stav:Nalezená=Ne ([:inconclusive=false:advanced=true]status:found_no)
- OFFLINE: Žádný ([:inconclusive=false:advanced=true])

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
geocaching.com: Logged in (Přihlášení bylo úspěšné) / PREMIUM
Geocaching.com Adventure Lab
- Geocaching.com date format: yyyy/MM/dd
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (188,3 GB free) v3 internal isDir(7 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (188,3 GB free) v3 internal isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (188,3 GB free) v3 external non-removable isDir(428 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (188,3 GB free) v3 internal isDir(3 entries)
- Public Folders: #11
  - BASE: /Documents/Cgeo (User-Defined)[/Documents/Cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo/document/primary%3ADocuments%2FCgeo, Av:true, files:>=20, dirs:>=8, totalFileSize:>=5,5 GB, free space: 188,3 GB, files on device: 15155200)
  - OFFLINE_MAPS: /Documents/Cgeo/maps (User-Defined)[/Documents/Cgeo/maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo%2Fmaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo%2Fmaps/document/primary%3ADocuments%2FCgeo%2Fmaps, Av:true, files:17, dirs:1, totalFileSize:5,5 GB, free space: 188,3 GB, files on device: 15155200)
  - OFFLINE_MAP_THEMES: /Documents/Cgeo/maps (User-Defined)[/Documents/Cgeo/maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo%2Fmaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo%2Fmaps/document/primary%3ADocuments%2FCgeo%2Fmaps, Av:true, files:17, dirs:1, totalFileSize:5,5 GB, free space: 188,3 GB, files on device: 15155200)
  - LOGFILES: /Documents/Cgeo/logfiles (Default)[/Documents/Cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo/document/primary%3ADocuments%2FCgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:10,2 KB, free space: 188,3 GB, files on device: 15155200)
  - GPX: /Documents/Cgeo/gpx (Default)[/Documents/Cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo/document/primary%3ADocuments%2FCgeo%2Fgpx, Av:true, files:2, dirs:0, totalFileSize:2,4 MB, free space: 188,3 GB, files on device: 15155200)
  - BACKUP: /Documents/Cgeo/backup (Default)[/Documents/Cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo/document/primary%3ADocuments%2FCgeo%2Fbackup, Av:true, files:7, dirs:3, totalFileSize:177,3 MB, free space: 188,3 GB, files on device: 15155200)
  - FIELD_NOTES: /Documents/Cgeo/field-notes (Default)[/Documents/Cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo/document/primary%3ADocuments%2FCgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 188,3 GB, files on device: 15155200)
  - SPOILER_IMAGES: /Documents/Cgeo/GeocachePhotos (Default)[/Documents/Cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo/document/primary%3ADocuments%2FCgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 188,3 GB, files on device: 15155200)
  - ROUTING_BASE: /Documents/Cgeo/routing (Default)[/Documents/Cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo/document/primary%3ADocuments%2FCgeo%2Frouting, Av:true, files:17, dirs:1, totalFileSize:951,3 MB, free space: 188,3 GB, files on device: 15155200)
  - ROUTING_TILES: /Documents/Cgeo/routing/segments4 (Default)[/Documents/Cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo/document/primary%3ADocuments%2FCgeo%2Frouting%2Fsegments4, Av:true, files:10, dirs:0, totalFileSize:951,2 MB, free space: 188,3 GB, files on device: 15155200)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 188,3 GB, files on device: -1)
- Map render theme path: paws_S.zip:paws_S/paws_S.xml
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #2
  - content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo (15. 1. 14:00):RW
  - content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FCgeo%2Fmaps (13. 3. 13:59):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v98, Size:45,8 MB) on system internal storage

--- End of system information ---
```

### Additional Information

Support ticket 569163

### PR DESCRIPTION
**Pull request by murggel**
## Description

don't show distance circles for waypoints, if the cache itselft does not need to show distance circles

## Related issues

fix #13117

### CODE REVIEW

File: main/src/cgeo/geocaching/models/Waypoint.java [hunk 1]
```diff
@@ -518,4 +518,14 @@ public int getMapDotMarkerBackgroundId() {
         return ConnectorFactory.getConnector(geocode).getCacheMapDotMarkerBackgroundId();
     }
 
+    public boolean applyDistanceRule() {
+        boolean applyDistanceRule = getWaypointType().applyDistanceRule();
+        if (applyDistanceRule) {
+            final Geocache parentCache = getParentGeocache();
+            if (parentCache != null) {
+                applyDistanceRule = parentCache.applyDistanceRule();
+            }
```
Comment (fm-sys) [inline main/src/cgeo/geocaching/models/Waypoint.java:527]: I guess this will not work in the way it should work. `Geocache.applyDistanceRule()` will only return true if the cache type is Tradi or the cache has corrected coordinates.

However, we explicitly want to show the circle for final waypoints which do not belong to a tradi. Maybe change your code to the following?:

```suggestion
            if (parentCache != null && parentCache.isArchived()) {
                applyDistanceRule = false;
            }
```

Comment (murggel) [reply main/src/cgeo/geocaching/models/Waypoint.java:527]: How about the connector-stuff?

Comment (fm-sys) [reply main/src/cgeo/geocaching/models/Waypoint.java:527]: > How about the connector-stuff?

Hm, that might be worth to keep. However, it would be bad if these decisions need to magically stay in sync between different classes. So maybe create a method `Geocache.mayApplyDistanceRule()` which can be used inside `Geocache.applyDistanceRule()` as well as `Waypoint.applyDistanceRule()`?

**Comment by murggel** [comment]
I will try to add some tests for that...

**Review by fm-sys — APPROVED** [review]
LGTM, thanks for working on it and especially for even adding unit tests 👍
