### PR TITLE
Fix #6344: Fix handler leaks

### LINKED ISSUE #6344: Lint Warnings may cause crash, display problem and memory leak
Hi,

I am using Lint to check for warnings in cgeo and found some warnings that can cause problems:
- [x] **Multi-catch with these reflection exceptions requires API level 19 (current min is 14) because they get compiled to the common but new super type `ReflectiveOperationException`. As a workaround either create individual catch statements, or catch `Exception`**
I found warnings of this category on [line 127 in FilterActivity.java](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/filter/FilterActivity.java#L127) [line 31 in CustomProgressDiag.java](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/ui/dialog/CustomProgressDialog.java#L31) and [line 150 in SortActionProvider.java](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/sorting/SortActionProvider.java#L150)
This warning may lead to crash as suggested in an [issue report of Android](https://code.google.com/p/android/issues/detail?can=1&q=153406&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&id=153406) (See comment 2)

- [x] **Format string `auth_register` is not a valid format string so it should not be passed to `String.format`**
This warning can be found in many places in the project like [line 274 in TokenAuthorizationActivity.java](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/activity/TokenAuthorizationActivity.java#L274).
I have checked [strings.xml](https://github.com/cgeo/cgeo/blob/master/main/res/values/strings.xml#L688). The string is really not a valid string format and the second parameter passed to the method would be ignored.

- [ ] **This Handler class should be static or leaks might occur (anonymous cgeo.geocaching.utils.DisposableHandler)**
This is a possible memory leak issue found [on line 399 in CacheListActivity.java](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/CacheListActivity.java#L399) and [line 165 in GPXImporter](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/files/GPXImporter.java#L165)
I have found some [related discussions from StackOverflow](http://stackoverflow.com/questions/11407943/this-handler-class-should-be-static-or-leaks-might-occur-incominghandler)

Hope this information can help. :)

### PR DESCRIPTION
**Pull request by UniQP**

### CODE REVIEW

File: main/src/cgeo/geocaching/MainActivity.java [hunk 1]
```diff
@@ -101,56 +102,62 @@
     private ConnectivityChangeReceiver connectivityChangeReceiver;
 
     private final UpdateLocation locationUpdater = new UpdateLocation();
+    private final Handler updateUserInfoHandler = new UpdateUserInfoHandler(this);
+    private final Handler firstLoginHandler = new FirstLoginHandler(this);
 
-    private final Handler updateUserInfoHandler = new Handler() {
+    private static final class UpdateUserInfoHandler extends Handler {
+        private final WeakReference<MainActivity> activityRef;
```
Comment (samueltardieu) [inline main/src/cgeo/geocaching/MainActivity.java]: It looks like it would be best to use `WeakReferenceHandler` here.

File: main/src/cgeo/geocaching/MainActivity.java [hunk 2]
```diff
@@ -195,21 +202,29 @@ public void accept(final Status gpsStatus) {
         }
     };
 
-    private final Handler firstLoginHandler = new Handler() {
+    private static final class FirstLoginHandler extends Handler {
+        private final WeakReference<MainActivity> activityRef;
```
Comment (samueltardieu) [inline main/src/cgeo/geocaching/MainActivity.java]: `WeakReferenceHandler`

File: main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java [hunk 3]
```diff
@@ -63,47 +64,67 @@
     private ProgressDialog requestTokenDialog = null;
     private ProgressDialog changeTokensDialog = null;
 
-    private final Handler requestTokenHandler = new Handler() {
+    private final Handler requestTokenHandler = new RequestTokenHandler(this);
+    private final Handler changeTokensHandler = new ChangeTokensHandler(this);
+
+    private static final class RequestTokenHandler extends Handler {
+        private final WeakReference<OAuthAuthorizationActivity> activityRef;
```
Comment (samueltardieu) [inline main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java]: `WeakReferenceHandler`

File: main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java [hunk 4]
```diff
@@ -63,47 +64,67 @@
...
+                    activity.showToast(activity.getErrAuthInitialize());
+                    startButton.setText(activity.getAuthStart());
+                }
             }
         }
+    }
 
-    };
+    private static final class ChangeTokensHandler extends Handler {
+        private final WeakReference<OAuthAuthorizationActivity> activityRef;
```
Comment (samueltardieu) [inline main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java]: `WeakReferenceHandler`

File: main/src/cgeo/geocaching/MainActivity.java (hunk 1 above)
Comment (UniQP) [inline main/src/cgeo/geocaching/MainActivity.java]: That's not possible, because `MainActivity` does not extend `Activity`, which is expected by `WeakReferenceHandler`.

File: main/src/cgeo/geocaching/MainActivity.java (hunk 2 above)
Comment (UniQP) [inline main/src/cgeo/geocaching/MainActivity.java]: That's not possible, because `MainActivity` does not extend `Activity`, which is expected by `WeakReferenceHandler`.

File: main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java (hunk 3 above)
Comment (UniQP) [inline main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java]: That's not possible, because `OAuthAuthorizationActivity` does not extend `Activity`, which is expected by `WeakReferenceHandler`.

File: main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java (hunk 4 above)
Comment (UniQP) [inline main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java]: That's not possible, because `OAuthAuthorizationActivity` does not extend `Activity`, which is expected by `WeakReferenceHandler`.

Comment (samueltardieu) [inline main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java]: Could you update `WeakReferenceHandler` so that it accepts an arbitrary type? There is no good reason to restrict it to an activity AFAICS.

You can rename `getActivity()` to `getReference()` to reflect the type change.

Comment (UniQP) [inline main/src/cgeo/geocaching/activity/OAuthAuthorizationActivity.java]: Done.

**Comment by pstorch** [comment]
@samueltardieu can you have a look again?
@UniQP a small merge conflict happend meanwhile.

**Comment by samueltardieu** [comment]
I'm testing it on the CI after a merge. Thanks for the heads up @pstorch.

**Comment by samueltardieu** [comment]
Thanks @UniQP!
