### PR TITLE
avoid NPE in refreshListChooser(), fixes #15676

### LINKED ISSUE #15676: NPE in cgeo.geocaching.unifiedmap.AbstractMapFragment.getViewport()
with recent nightlies (at least 1 week) I have many crashs caused by NPE in cgeo.geocaching.unifiedmap.AbstractMapFragment.getViewport()

Those happen in different situations, e.g. editing personal note, opening cache details, going back from cache to map.

Some stacktraces:
java.lang.NullPointerException: Attempt to invoke virtual method 'cgeo.geocaching.location.Viewport cgeo.geocaching.unifiedmap.AbstractMapFragment.getViewport()' on a null object reference
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.refreshListChooser(UnifiedMapActivity.java:571)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.reloadCachesAndWaypoints(UnifiedMapActivity.java:477)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.access$000(UnifiedMapActivity.java:128)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity$1.onReceive(UnifiedMapActivity.java:266)
	at cgeo.geocaching.service.GeocacheChangedBroadcastReceiver.onReceive(GeocacheChangedBroadcastReceiver.java:35)

java.lang.NullPointerException: Attempt to invoke virtual method 'cgeo.geocaching.location.Viewport cgeo.geocaching.unifiedmap.AbstractMapFragment.getViewport()' on a null object reference
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.refreshListChooser(UnifiedMapActivity.java:571)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.$r8$lambda$0tdmED8uHBT03g53if-rjSKFSTs(UnifiedMapActivity.java:0)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity$$ExternalSyntheticLambda30.run(R8$$SyntheticClass:0)
	at cgeo.geocaching.utils.livedata.CollectionLiveData.lambda$observeForNotification$1(CollectionLiveData.java:92)
	at cgeo.geocaching.utils.livedata.CollectionLiveData.$r8$lambda$O5YFKMwJuUNg_jb2gA0FxU212LY(CollectionLiveData.java:0)
	at cgeo.geocaching.utils.livedata.CollectionLiveData$$ExternalSyntheticLambda1.onChanged(R8$$SyntheticClass:0)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'cgeo.geocaching.location.Viewport cgeo.geocaching.unifiedmap.AbstractMapFragment.getViewport()' on a null object reference
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.refreshListChooser(UnifiedMapActivity.java:571)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.reloadCachesAndWaypoints(UnifiedMapActivity.java:477)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.onResume(UnifiedMapActivity.java:1192)

### PR DESCRIPTION
**Pull request by ztNFny**
attempt to fix a NPE in UnifiedMapActivity which was apparently introduced by a conflict resolution merge in https://github.com/cgeo/cgeo/commit/74d93a20d0408549ee4442c811f37332cbefdfc8

### CODE REVIEW

**Comment by ztNFny** [comment]
Retest this please

**Comment by ztNFny** [comment]
retest this please

File: main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java [hunk 1]
```diff
@@ -571,9 +571,8 @@ private String calculateTitle() {
     private void refreshListChooser() {
         //try to get count of visible caches
         int visibleCaches = 0;
-        final Viewport viewport = mapFragment.getViewport();
-        if (mapFragment != null && viewport != null && viewModel != null) {
-            visibleCaches = viewModel.caches.readWithResult(viewport::count);
+        if (mapFragment != null && mapFragment.getViewport() != null && viewModel != null) {
+            visibleCaches = viewModel.caches.readWithResult(mapFragment.getViewport()::count);
```
Comment (moving-bits) [inline main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java:575]: out of curiosity: what is the difference between `mapFragment.getViewport()::count` and `viewport::count` with `viewport` being set to `mapFragment.getViewport()`?

Comment (ztNFny) [reply main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java:575]: There isn't any. 

mapFregment may be null, so that needs a null check before getViewport(). And the variable is used only once, so no point in creating it.

Comment (moving-bits) [reply main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java:575]: Ah, you're right, `mapFragment` could be null, crashing in line 574 then - had missed that. Thanks for clarifying and for the fix.
