### PR TITLE
use toggle button group in quicksettings

### LINKED ISSUE #10742: Material theming: Routing buttons in map quick settings are all-orange
## Bug description 
The routing mode buttons in map quick settings currently are all-orange, thus it's pretty hard to see which one is the active button.

That may change if we decide upon a different look for the buttons (see #10739), but we should keep this bug in mind and fix it (if still needed), when the look for out buttons has been decided upon.

### PR DESCRIPTION
**Pull request by fm-sys**
fix #10742

### CODE REVIEW

File: main/src/cgeo/geocaching/maps/MapSettingsUtils.java [hunk 1]
```diff
@@ -158,6 +159,50 @@ public void setValue() {
         }
     }
 
+    private static class ToggleButtonWrapper<T> {
```
Comment (eddiemuc) [inline main/src/cgeo/geocaching/maps/MapSettingsUtils.java:162]: @fm-sys in my understanding this would replace the ToggleButtonGroup, right? Can you externalize it so it can be used in other places as well (e.g. the filter activity...)? Or should I do that later myself?

Comment (fm-sys) [reply main/src/cgeo/geocaching/maps/MapSettingsUtils.java:162]: First of all, it's a replacement for `ButtonController` (an internal class of `MapSettingsUtils`). But if it looks suitable for you, I can externalize it as well...

Comment (eddiemuc) [reply main/src/cgeo/geocaching/maps/MapSettingsUtils.java:162]: I see now that it is not a view itself.

**Comment by fm-sys** [comment]
grafik

**Comment by fm-sys** [comment]
I removed the "(Current: xxx)" from the Routing mode title, as it was kind of inconsistent and I think the icons are quite clear anyway (we had different icons at the time we implemented the title text). If you tell me, that we definitely need to keep it, I can re-add it for sure...

**Comment by moving-bits** [comment]
Leaving out the description for routing mode buttons is ok for me (as I do know their meaning ;-)), but I remember us having some discussion about the icons, which explicitly led to adding that text.

@Lineflyer 
What is your feedback from a support perspective?

**Comment by Lineflyer** [comment]
> What is your feedback from a support perspective?

I think we can omit the description of current mode.
I think the buttons are very understandable.

**Comment by Lineflyer** [comment]
BTW:
IMHO we could also remove/rephrase the text below regarding installation of BRouter as we now have the internal engine (which is the preferable way IMHO).

**Comment by eddiemuc** [comment]
Can we merge this one rather quickly? Right now the buttons are almost unusable in master.
