### PR TITLE
try to fix #11206: add some guards

### LINKED ISSUE #11206: SQLiteException
Reported for current series of beta versions, 60 occurrences for 3 users, Android 10-11 

```
android.database.sqlite.SQLiteException: 
  at android.database.sqlite.SQLiteConnection.nativePrepareStatement (Native Method)
  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement (SQLiteConnection.java:1463)
  at android.database.sqlite.SQLiteConnection.prepare (SQLiteConnection.java:901)
  at android.database.sqlite.SQLiteSession.prepare (SQLiteSession.java:590)
  at android.database.sqlite.SQLiteProgram.<init> (SQLiteProgram.java:62)
  at android.database.sqlite.SQLiteQuery.<init> (SQLiteQuery.java:37)
  at android.database.sqlite.SQLiteDirectCursorDriver.query (SQLiteDirectCursorDriver.java:46)
  at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory (SQLiteDatabase.java:2063)
  at android.database.sqlite.SQLiteDatabase.rawQuery (SQLiteDatabase.java:2002)
  at cgeo.geocaching.storage.DataStore.loadWaypoints (DataStore.java:4320)
  at cgeo.geocaching.maps.CGeoMap.doLoadRun (CGeoMap.java:1300)
  at cgeo.geocaching.maps.CGeoMap.access$2100 (CGeoMap.java:121)
  at cgeo.geocaching.maps.CGeoMap$LoadRunnable.runWithMap (CGeoMap.java:1249)
  at cgeo.geocaching.maps.CGeoMap$DoRunnable.run (CGeoMap.java:1471)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:923)
```

### PR DESCRIPTION
**Pull request by eddiemuc**
try to fix #11206: add some guards

### CODE REVIEW

File: main/src/cgeo/geocaching/storage/DataStore.java [hunk 1]
```diff
@@ -4360,7 +4360,7 @@ private static StringBuilder whereGeocodeIn(final Collection<String> geocodes) {
         }
         query.append(" FROM ").append(dbTableWaypoints).append(", ").append(dbTableCaches).append(" WHERE ").append(dbTableWaypoints)
                 .append(".geocode == ").append(dbTableCaches).append(".geocode AND ").append(where)
-                .append(" LIMIT " + (Settings.getKeyInt(R.integer.waypoint_threshold_max) * 2));  // Hardcoded limit to avoid memory overflow
+                .append(" LIMIT " + (Math.max(10, Settings.getKeyInt(R.integer.waypoint_threshold_max)) * 2));  // Hardcoded limit to avoid memory overflow
```
Comment (moving-bits) [inline main/src/cgeo/geocaching/storage/DataStore.java:4363]: Would that mean, that no more than 10 waypoints will be shown on the map ever again?
I know of multi caches which have 40 or 50 waypoints for a single cache (see GC24CQN for example), those would become unplayable, wouldn't they?

Comment (eddiemuc) [reply main/src/cgeo/geocaching/storage/DataStore.java:4363]: No, it just means that the limit will.never be less than 10, regardless of the setting. I put this guard to prevent the theoretical case that the setting returns e.g. a negative number

Comment (moving-bits) [reply main/src/cgeo/geocaching/storage/DataStore.java:4363]: Oops, my bad, I've read `min` somehow... Sorry!
