### PR TITLE
Mitigate Runtime exception for some devices

### LINKED ISSUE #7460: RuntimeException related to CachePopup.onCreate
This problem report from Google Play has the highest occurence (besides the NPE on Resume issues, which are hopefully already fixed).

Version: 2019.02.23 (and also beta 2019.03.30-RC1)
```
java.lang.RuntimeException: 
 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2822)
 
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2897)
 
  at android.app.ActivityThread.-wrap11 (Unknown Source)
 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1598)
 
  at android.os.Handler.dispatchMessage (Handler.java:105)
 
  at android.os.Looper.loop (Looper.java:251)
 
  at android.app.ActivityThread.main (ActivityThread.java:6572)
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
Caused by: android.util.AndroidRuntimeException: 
 
  at android.support.v7.app.AppCompatDelegateImplV7.throwFeatureRequestIfSubDecorInstalled (AppCompatDelegateImplV7.java:1683)
 
  at android.support.v7.app.AppCompatDelegateImplV7.requestWindowFeature (AppCompatDelegateImplV7.java:585)
 
  at android.support.v7.app.AppCompatActivity.supportRequestWindowFeature (AppCompatActivity.java:228)
 
  at cgeo.geocaching.activity.AbstractActivity.onCreateCommon (AbstractActivity.java:134)
 
  at cgeo.geocaching.activity.AbstractActivity.onCreate (AbstractActivity.java:114)
 
  at cgeo.geocaching.CachePopup.onCreate (CachePopup.java:40)
 
  at android.app.Activity.performCreate (Activity.java:6975)
 
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1214)
 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2775)
```

### PR DESCRIPTION
**Pull request by rsudev**
Some devices throw an exception when requesting
this window feature for unknown and currently not
reproducible reasons. Catch and log it.

Fixes #7460

### CODE REVIEW

File: main/src/cgeo/geocaching/CachePopup.java [hunk 1]
```diff
@@ -38,7 +40,11 @@ void showDialog() {
     @Override
     public void onCreate(final Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
-        supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
+        try {
+            supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
+        } catch (final AndroidRuntimeException ex) {
+            Log.e("Error requesting indeterminate progress", ex);
```
Comment (moving-bits) [inline main/src/cgeo/geocaching/CachePopup.java]: Shouldn't that log "Error requesting Window.FEATURE_NO_TITLE"?

Comment (rsudev) [reply main/src/cgeo/geocaching/CachePopup.java]: It should of course :)
