### PR TITLE
Fix #10688: Adapt patterns to changes in login page

### LINKED ISSUE #10688: [Nightly(?)] Unable to login to geocaching.com
## Bug description 
Just failed to update the offline saved listing of a Mystery.
Loading another not offline stored Mystery resulted in "This cache is for Premium members only."
Thus I tried to update authorization in ``Services`` => ``Geocaching.com``, which resulted in ``Login failed: Failed Login page parsing``.

## c:geo version 
2021.05.19-NB-df61a4d

## Reproducible 
Yes

## Additional context 
Upload button for personal notes is missing, too.
Change(s) must have happened in the last two hours, cause at 10 p.m. everything was working fine.
Login via browser is working fine, even from mobile.
If more debug info is needed, just let me know.

### PR DESCRIPTION
**Pull request by rsudev**
## Description
Adapt parser patterns to changes in geocaching.com page

## Related issues
#10688

### CODE REVIEW

**Comment by Lineflyer** [comment]
@rsudev Thanks for the quick PR. Some login related tests seem to still fail however. More changes involved?

File: main/src/cgeo/geocaching/connector/gc/GCConstants.java [hunk 1]
```diff
@@ -75,9 +75,10 @@
     static final String PATTERN_GC_CHECKER = "ctl00_ContentBody_lblSolutionChecker";
 
     // Info box top-right
-    public static final Pattern PATTERN_LOGIN_NAME = Pattern.compile("\\swindow(?>\\.|\\[')headerSettings(?>'\\])?\\s*=\\s*\\{[\\S\\s]*\"username\":\\s*\"([^\"]*)\",?[\\S\\s]*\\}");
+    public static final Pattern PATTERN_LOGIN_NAME = Pattern.compile("\\swindow(?>\\.|\\[')chromeSettings(?>'\\])?\\s*=\\s*\\{[\\S\\s]*\"username\":\\s*\"([^\"]*)\",?[\\S\\s]*\\}");
```
Comment (UniQP) [inline main/src/cgeo/geocaching/connector/gc/GCConstants.java:78]:
```suggestion
    public static final Pattern PATTERN_LOGIN_NAME = Pattern.compile("\\swindow(?>\\.|\\[')(?headerSettings|chromeSettings)(?>'\\])?\\s*=\\s*\\{[\\S\\s]*\"username\":\\s*\"([^\"]*)\",?[\\S\\s]*\\}");
```
That would allow to match both variants without adapting any other code. We can simplify the RegEx as soon as all sites changed.

**Review by UniQP — CHANGES_REQUESTED** [review]

**Comment by UniQP** [comment]
@rsudev I changed the regular expressions to match the old and new variant.
@Lineflyer Tests are green now.

**Comment by Lineflyer** [comment]
Thanks @UniQP 
@rsudev Are you fine with the approach. Looks reasonable to me.

**Comment by rsudev** [comment]
@UniQP Thanks for that! Fine with me :)
