### PR TITLE
Fixed #5339 no feedback no personal note upload

### LINKED ISSUE #5339: Upload of Personal Note fails, but says it did
If one tries to upload a personal note, despite not connected to the internet, one still get a success message "Personal note uploaded".

reproducable: always
occurs since: quite a while ago
Device/Android: HTC One m7, Android 5.1 (Google Play Edition)

### PR DESCRIPTION
**Pull request by pstorch**
Evaluating return value from Connector uploadPersonalNote to present correct message.

### CODE REVIEW

File: main/src/cgeo/geocaching/CacheDetailActivity.java [hunk 1]
```diff
@@ -1553,13 +1553,18 @@ private void uploadPersonalNote() {
...
+                        final boolean success = con.uploadPersonalNote(cache);
+
+                        final Message msg = Message.obtain();
+                        final Bundle bundle = new Bundle();
+                        if (success) {
+                            bundle.putString(SimpleCancellableHandler.MESSAGE_TEXT, CgeoApplication.getInstance().getString(R.string.cache_personal_note_upload_done));
+                        } else {
+                            bundle.putString(SimpleCancellableHandler.MESSAGE_TEXT, CgeoApplication.getInstance().getString(R.string.cache_personal_note_upload_error));
+                        }
+                        msg.setData(bundle);
```
Comment (samueltardieu) [inline main/src/cgeo/geocaching/CacheDetailActivity.java]: I would have simply written:

```java
  bundle.putString(SimpleCancellableHandler.MESSAGE_TEXT, CgeoApplication().getInstance().getString(success ?
    R.string.cache_personal_note_upload_done : R.string.cache_personal_note_upload_error));
```

to avoid repeating the same code.

**Comment by samueltardieu** [comment]
Please use a header line such as

```
fix #5339: no feedback no personal note upload
```

in the commit message, so that a simple "git log --pretty=oneline" gives meaningful information.

**Comment by samueltardieu** [comment]
ok to test

File: main/src/cgeo/geocaching/CacheDetailActivity.java (hunk 1 above)
Comment (pstorch) [inline main/src/cgeo/geocaching/CacheDetailActivity.java]: Yes, it's better this way.

File: main/src/cgeo/geocaching/CacheDetailActivity.java [hunk 2]
```diff
@@ -1553,13 +1553,14 @@ private void uploadPersonalNote() {
...
                     final IConnector con = ConnectorFactory.getConnector(cache);
                     if (con.supportsPersonalNote()) {
-                        con.uploadPersonalNote(cache);
+                        final boolean success = con.uploadPersonalNote(cache);
+
+                        final Message msg = Message.obtain();
+                        final Bundle bundle = new Bundle();
+                        bundle.putString(SimpleCancellableHandler.MESSAGE_TEXT, CgeoApplication.getInstance().getString(success ? R.string.cache_personal_note_upload_done : R.string.cache_personal_note_upload_error));
+                        msg.setData(bundle);
+                        myHandler.sendMessage(msg);
```
Comment (SammysHP) [inline main/src/cgeo/geocaching/CacheDetailActivity.java]: If this method is called and the connector does not support personal notes, no message would be sent, thus the handler would wait infinitely.

IMHO a message should be sent in any case, either with a success or a failure message (like in this patch) or with a "not supported" message as a dirty way of handling this situation in a case that shouldn't happen (because the button to upload the note should not be visible unless it is possible).

Comment (pstorch) [inline main/src/cgeo/geocaching/CacheDetailActivity.java]: In CacheDetailActivity the upload button is only shown if the connector supports it.
See line 1474

Comment (pstorch) [inline main/src/cgeo/geocaching/CacheDetailActivity.java]: But I can add a Message "just in case" the disabling didn't work. Should I?

Comment (SammysHP) [inline main/src/cgeo/geocaching/CacheDetailActivity.java]: IMHO it would be a safer behavior. What do you think, @samueltardieu?

Comment (pstorch) [inline main/src/cgeo/geocaching/CacheDetailActivity.java]: What about simply calling `myHandler.cancel()` in the else case?

Comment (rsudev) [inline main/src/cgeo/geocaching/CacheDetailActivity.java]: I would suggest a 'not supported' message. This handles the unlikely case in a smooth and understandable fashion without too much effort.

**Comment by rsudev** [comment]
ok to test

File: main/src/cgeo/geocaching/CacheDetailActivity.java (hunk 2 above)
Comment (pstorch) [inline main/src/cgeo/geocaching/CacheDetailActivity.java]: A general "Not supported" message or  specific one like "Upload of personal note not supported"?

Comment (rsudev) [inline main/src/cgeo/geocaching/CacheDetailActivity.java]: I'd rather be specific.

**Comment by pstorch** [comment]
I've added a "Upload of personal note not supported" in the case where the upload button could be pressed but the upload is not supported by the connector.
This is hard to test, because the upload button usually prohibits it. I've temporarly removed this check (not commited though) to see the new error message.

**Comment by samueltardieu** [comment]
I don't think we need defensive programming at the point where we schedule a localized error message for a condition that can never happen. In which case could the button be enabled *and* `con.supportsPersonalNote()` be false? Isn't the same condition used to enable the button?

In this case, I'd be in favour to crash plain and simple, this is a logic bug in the application and I'd prefer to know about it from the crash traces.

**Comment by pstorch** [comment]
Enablind the upload button is done with this condition:
```
    if (cache.isOffline() && ConnectorFactory.getConnector(cache).supportsPersonalNote()) {
                personalNoteUpload.setVisibility(View.VISIBLE);
```
So technically it can't happen.

**Comment by pstorch** [comment]
Any agreement what we should do? 
Keep this dialog just in case, silently close the handler or ignore this condition?

**Comment by samueltardieu** [comment]
Since `con.supportsPersonalNote()` is necessarily true, I'd remove the `if` altogether.

**Comment by pstorch** [comment]
Ok, I've removed the `if` completely.

**Comment by Bananeweizen** [comment]
thanks
