### PR TITLE
Resolve false triggerings of action bar hide (rel. to #14066)

### LINKED ISSUE #14066: Early feedback about action bar hiding
### Describe your problem!

Google map:
- [x] zoom by double tap triggers action bar hiding 
- [x] zoom using zoom controls triggers action bar hiding 
- [x] compass is hidden behind actionbar 

(this does not happen with Mapsforge maps)

General:
- [x] the current animation is quite "bumpy". Such an animation IMHO must look really smooth or users will not understand what happened on the screen.
- Having tested it a bit, it indeed feels like a great improvement for small landscape layouts, however I personally won't like to see it on tablets or portrait layouts. UPDATE: I'll get used to it. Since the above bugs are fixed, I can live with this feature :)

### How to reproduce?

-

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Yes

### c:geo Version

NB2023.03.06

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Partly resolve #14066 by trying to remove false triggerings of action bar hide on double tapping or tapping zoom controls. Implemented for GMv2 only to test this solution.

@fm-sys 
Can you give it a try in your environment? Thanks.

### CODE REVIEW

File: main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java [hunk 1]
```diff
@@ -425,24 +433,13 @@ public boolean onSingleTapUp(final MotionEvent e) {
                         final Point waypointPoint = googleMap.getProjection().toScreenLocation(new LatLng(closest.getCoord().getCoords().getLatitude(), closest.getCoord().getCoords().getLongitude()));
                         if (insideCachePointDrawable(p, waypointPoint, closest.getMarker(0).getDrawable())) {
                             onCacheTapListener.onCacheTap(closest.getCoord());
```
Comment (fm-sys) [inline main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java:435]: Works fine! Maybe move the cache tap listener as well to fix #7569?

Comment (moving-bits) [reply main/src/main/java/cgeo/geocaching/maps/google/v2/GoogleMapView.java:435]: Thanks for reviewing.

I had tried to move `cacheTapListener` to `mapOnClickListener` as well, but that will trigger the enormous delay when tapping on a cache marker, which (according to the comment in the source) probably was the reason to write the `GestureListener` in the first place. Thus I reverted to stay with triggering action bar hiding/unhiding.
