### PR TITLE
Reactivate the contacts plugin (fix #7193)

### LINKED ISSUE #7193: Raise Target SDK to 26 for contacts plugin (or reintegrate into main app)
Hello Google Play Developer, 
In October, we announced updates to our Permissions policy that will limit which apps are allowed to request Call Log and SMS permissions. This policy will impact one or more of your apps. 
Only an app that has been selected as a user's default app for making calls or text messages, or whose core functionality is approved for one of the exception use cases, will be able to request access to Call Log or SMS permissions. 
Action required 
Below, we've listed apps from your catalog which do not meet the requirements for permission requests. Please remove any disallowed or unused permissions from your app's manifest (specified below), migrate to an alternative implementation (e.g. SMS Retriever API for most cases of OTP verification), or evaluate if your app qualifies for an exception. 
Next steps

Read through the Permissions policy and the Play Console Help Center article, which describes intended uses, exceptions, invalid uses, and alternative implementation options for usage of Call Log or SMS permissions.

Update your app or submit a Permissions Declaration Form.

Option 1) If your app does not require access to Call Log or SMS permissions: Make appropriate changes to your app by removing the specified permissions from your app's manifest or migrating to an available alternative implementation by January 9, 2019. 

Option 2) If your app is a default handler or you believe your app qualifies for an exception: Please submit a request via the Permissions Declaration Form. You do not need to have implemented APK changes in order to submit a form. Declaration Forms received by January 9, 2019 may be eligible for additional time to make changes to bring their app(s) into compliance. If you have recently submitted a Permissions Declaration Form, we are in the process of reviewing your information and will respond to your application.

Make sure that your app is otherwise compliant with all other Developer Program Policies to prevent your app from being removed.

Alternatively, you can choose to unpublish the app. 
Our Developer Program Policies are designed to provide a safe and secure experience for our users while also giving developers the tools they need to succeed. That is why we will remove apps that violate our policies. In cases of repeated or serious violations of our policies, we may also terminate your developer account and any related developer accounts. 
We appreciate your willingness to partner with us as we make these improvements to better protect users. 
Affected apps 
Affected apps and permissions are listed below, up to 20; if you have additional apps, please ensure that they are also compliant with the Permissions policy. 

cgeo.contacts READ_CALL_LOG

### LINKED ISSUE #7582: Remove contacts plugin from useful apps list
Prompted by the recent addition of 'GPS Locker' to the utility programs, I had a quick look at some of the others available. I only looked at a couple, but....

"Contacts plugin" - doesn't exist in playstore anymore.
"PQ Generator" - hasn't worked for about 6 months.

Maybe an audit of all utils is in order?

### PR DESCRIPTION
**Pull request by bekuno**
It was stated in https://github.com/cgeo/cgeo/issues/7582#issuecomment-487609065:
	As long as we support Api versions without permission requests, we IMO cannot integrate it
	into the main app based on the same arguments we had for the separation initially.
My internal test showed that this is correct.

fixes #7193 (Raise Target SDK to 26 for contacts plugin (or reintegrate into main app))
fixes #7582 (Remove contacts plugin from useful apps list)
 -> not remove, but reactivate

- build.gradle based on PR #7236
- adapt PermissionHandler and PermissionRequestContext from main for the contacts need
- inplement contacts permission handling in ContactsActivity
- minor code optimizations (Checkstyle suggestions) in selectContact and getContacts

tested on Android 4.3, 7.0 and 9

The *.apk is located at
https://ci.cgeo.org/view/All%20jobs/job/cgeo-contacts%20release/8/

### CODE REVIEW

**Comment by bekuno** [comment]
The latest *.apk is located at
https://ci.cgeo.org/view/All%20jobs/job/cgeo-contacts%20release/9/

**Comment by bekuno** [comment]
retest this please

File: cgeo-contacts/src/cgeo/contacts/ContactsActivity.java [hunk 1]
```diff
@@ -127,12 +137,9 @@ private void openContactAndFinish(final int id) {
                         !StringUtils.equalsIgnoreCase(foundName, displayName) ? foundName + " (" + displayName + ")" : foundName));
             }
         } catch (final Exception e) {
-            Log.e(LOG_TAG, "ContactsActivity.getContactId", e);
-        } finally {
-            if (cursor != null) {
-                cursor.close(); // no Closable Cursor below sdk 16
```
Comment (moving-bits) [inline cgeo-contacts/src/cgeo/contacts/ContactsActivity.java]: Haven't checked all, but stumbled upon this line: Why don't you close the cursor any more?

Comment (bekuno) [reply cgeo-contacts/src/cgeo/contacts/ContactsActivity.java]: His visibility has changed.
Previously it was instantiated outside the try block, now inside it.

From code inspection - "'try finally' replaceable with 'try' with resources inspection":
"Reports try finally statements which can use Java 7 Automatic Resource Management. A quickfix is available to convert the try finally statement into a try with resources statement.
This inspection only reports if the project or module is configured to use a language level of 7.0 or higher."

**Comment by bekuno** [comment]
@rsudev Please check the code for correct permissing handling.

@Lineflyer Please test the apk with different Android versions.
Do we need an advanced CI configuration to create an apk that can be uploaded to Google Play?

File: cgeo-contacts/src/cgeo/contacts/ContactsActivity.java (hunk 1 above)
Comment (moving-bits) [reply cgeo-contacts/src/cgeo/contacts/ContactsActivity.java]: Ah, cool, didn't know that feature - thanks!

**Comment by Lineflyer** [comment]
@bekuno 
I quickly checked the APK and the permission handling seems to work. Thanks for taking care of this topic. In contrast to other permission requests (which are obligatory for c:geo to work) the contact permission request should maybe also offer the option "Cancel" in addition to "Ask me again"?! Currently the user might be stuck in an endless circle if he declines the request.

Regarding the CI I will take a look. IMHO we already have this available, but its long time ago since I last published a plugin. I will find out.
I am also unsure about the branch handling in this case. But AFAIR we did not use the branches (release vs. master) as we do for the main app but just published from master. Thus your PR is fine with targeting master.

**Comment by Lineflyer** [comment]
I will merge this to test building with CI from master.
@rsudev You might still want to review the changes as requested by @bekuno

**Comment by bekuno** [comment]
@Lineflyer 
> In contrast to other permission requests (which are obligatory for c:geo to work) the contact permission request should maybe also offer the option "Cancel" in addition to "Ask me again"?! Currently the user might be stuck in an endless circle if he declines the request.

The user should decide if he gives the read access or not.
He can select the option "do not ask again" from the second call.
Then you have an aditional AlertDialog with a "close" button.

**Comment by Lineflyer** [comment]
@bekuno 
Oh, perfect. Did not try this one out....then all is fine for me.
