### PR TITLE
Increase history limit 

### LINKED ISSUE #12455: [Nightly] View history limited to 9 entries
### Describe your problem!

One can get a list of ``Recently Viewed Caches`` by clicking on the magnifying glass in the header of the ``Home`` page.
As long as you do *not* enter any search text, you get your valuable view history.
Once upon a time, this list was delightfully long - which made it extremely useful, especially on longer caching tours.
But, most regretfully, it is limited to 9 entries since ... hmm ... the other day.

I in fact thought, this has already been reported with #12157, but seemingly I was wrong. ;)

This list should at least get the length it previously had (to be honest, I don't exactly know how long it was, but as I never missed a looked up cache in there, I would consider the last 100 caches as an absolute minimum, but would be more happy with even more ;) ).

### How to reproduce?

1. Go to ``Home`` page
2. click on the ``Magnifier``
3. do *not* enter any text (you will get a list of ``Recently Viewed Caches``)
4. try to scroll the view history list ...

### Actual result after these steps?

List is limited to 9 entries and will not scroll

### Expected result after these steps?

List should be way longer - in order to re-enable the user to really be able to trace back his view history.

### Reproducible

Yes

### c:geo Version

2022.01.01-NB-5f857a5

### System information

```text
Device:
-------
- Device type: VOG-L29 (VOG-L29EEA, HUAWEI)
- Available processors: 8
- Android version: 10
- Android build: VOG-L29 10.1.0.150(C431E19R2P5)
- Screen resolution: 1080x2147px (423x841dp)
- Pixel density: 2.55
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: disabled - 21.48.15 (100400-414534850)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:288
- Set language: en_DE (system default)
- System date format: dd/MM/y
- Time zone: GMT+01:00
- Debug mode active: no
- Last backup: 1 Jan, 23:37
- Routing mode: Car
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Map: _  DE BaWü Vosges (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:0123-4567:Locus/mapsVector/_  DE BaWü Vosges.map
  - Atts: Maps: (c)Christian Kernbeis, Themes: (c)Tobias Kuehn, www.openandromaps.org 2012-2021
  - Theme: Elements F140 L120 S110 EB.xml

Filters:
-------
- Hide waypoints: visited
- LIVE: Cache Name:Contains:koffer,Cache Type:Multi ([:inconclusive=false:advanced=true]AND(name:koffer:contains;type:MULTI))
- OFFLINE: None ([:inconclusive=false:advanced=true])

Stored Filters (#8):
- - Live (Hide Found, Own & Archived): [- Live \(Hide Found, Own & Archived\):inconclusive=false:advanced=true]AND(status:owned_no:found_no:has_offline_found_log_no:exclude_archived))
- Description:Leiter: [Description\:Leiter:inconclusive=false:advanced=false]AND(description:Leiter:contains))
- HQ + Jasmer: [HQ + Jasmer:inconclusive=false:advanced=false]AND(stored_list:129:337:356:36))
- HQ and Must Haves: [HQ and Must Haves:inconclusive=false:advanced=true]AND(stored_list:129:337:36:155))
- Matrix Needed (List): [Matrix Needed \(List\):inconclusive=false:advanced=false]AND(stored_list:155))
- Matrix needed 3.5/3.5: [Matrix needed 3.5/3.5:inconclusive=false:advanced=false]AND(terrain:3.5:3.5;difficulty:3.5:3.5))
- Matrix needed 3/4: [Matrix needed 3/4:inconclusive=false:advanced=false]AND(terrain:3.0:3.0;difficulty:4.0:4.0))
- Matrix needed 4/1.5: [Matrix needed 4/1.5:inconclusive=false:advanced=false]AND(terrain:4.0:4.0;difficulty:1.5:1.5))

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
- Geocaching.com date format: dd MMM yy
- Routing: external / BRouter installed: true
- Installed c:geo plugins: contacts

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (46,2 GB free) v3 internal isDir(8 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (46,1 GB free) v3 external non-removable isDir(5 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (46,1 GB free) v3 external non-removable isDir(1622 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (46,2 GB free) v3 internal isDir(8 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=12, dirs:>=12, totalFileSize:>=1,3 GB, free space: 46,1 GB, files on device: 13278715)
  - OFFLINE_MAPS: ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector (User-Defined)[‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector::]] (Uri:content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector/document/0123-4567%3ALocus%2FmapsVector, Av:true, files:450, dirs:4, totalFileSize:22,8 GB, free space: 147,5 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector/_themes/Elevate4 (User-Defined)[‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector/_themes/Elevate4[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4::]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4/document/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4, Av:true, files:418, dirs:1, totalFileSize:3,4 MB, free space: 147,5 GB, files on device: 0)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:119 B, free space: 46,1 GB, files on device: 13278715)
  - GPX: /Download/GPX (User-Defined)[/Download/GPX[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX/document/primary%3ADownload%2FGPX, Av:true, files:2, dirs:0, totalFileSize:34,6 KB, free space: 46,1 GB, files on device: 13278715)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=17, dirs:>=7, totalFileSize:>=2,2 GB, free space: 46,1 GB, files on device: 13278715)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:68, dirs:0, totalFileSize:140,8 KB, free space: 46,1 GB, files on device: 13278715)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 46,1 GB, files on device: 13278715)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:11, dirs:0, totalFileSize:109,9 KB, free space: 46,1 GB, files on device: 13278715)
  - ROUTING_TILES: ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Android/media/btools.routingapp/brouter/segments4 (User-Defined)[‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Android/media/btools.routingapp/brouter/segments4[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3AAndroid%2Fmedia%2Fbtools.routingapp%2Fbrouter%2Fsegments4::]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3AAndroid%2Fmedia%2Fbtools.routingapp%2Fbrouter%2Fsegments4/document/0123-4567%3AAndroid%2Fmedia%2Fbtools.routingapp%2Fbrouter%2Fsegments4, Av:true, files:20, dirs:0, totalFileSize:1,3 GB, free space: 147,5 GB, files on device: 0)
- TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 46,2 GB, files on device: -1)
- Map render theme path: Elements F140 L120 S110 EB.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #5
  - content://com.android.externalstorage.documents/tree/0123-4567%3AAndroid%2Fmedia%2Fbtools.routingapp%2Fbrouter%2Fsegments4 (25 Dec 2021, 21:59):RW
  - content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX (24 May 2021, 00:17):RW
  - content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4 (20 May 2021, 23:38):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (20 May 2021, 23:37):RW
  - content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector (20 May 2021, 23:37):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v98, Size:437,5 MB) on system internal storage
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by fm-sys**
fix #12455

### CODE REVIEW

File: main/src/cgeo/geocaching/settings/Settings.java [hunk 1]
```diff
@@ -98,6 +98,8 @@
 
     public static final int DAYS_TO_SECONDS = 24 * 60 * 60;
 
+    private static final int HISTORY_SIZE = 10;
```
Comment (moving-bits) [inline main/src/cgeo/geocaching/settings/Settings.java:101]: still 10?

Comment (fm-sys) [reply main/src/cgeo/geocaching/settings/Settings.java]: Oh 😅 I guess it makes sense to commit all changes before pushing :)

This happens when coding on two topics at the same time... 😂

Comment (moving-bits) [reply main/src/cgeo/geocaching/settings/Settings.java]: ;-)
