### PR TITLE
fix #17396, fix #17395: fix edge-2-edge glitches within map and wherigo status bar

### LINKED ISSUE #17395: Edge-2-Edge: Wherigo Status Bar no longer visible when Wherigo is running
Wherigo Status Bar is no longer visible on main screens when a Wherigo is running.

This is due to Edge-2-Edge-Mode: bar is currently pushed "upward" (above activity_content) and thus not visible

### LINKED ISSUE #17396: [Nightly] edge2edge: content of "Navigate to" hidden behind header and Android's nav buttons
### Describe your problem!

Seems as if there are two different scenarios:
1.: opened directly from the details page via "Navigate" button in the header
hides the buttons for individual route and quick settings behind Android's nav buttons plus the distance fields behind the header:

Image

2.: from details first open compass, then use "Show on map"
hides the buttons for individual route and quick settings only:

Image
 
Although Android's nav buttons can hardly be seen on the pictures, they are there.  ;)
When zooming in, you can e. g. see the circle around the quick settings gear icon (which is not clickable anymore).

### How to reproduce?

Open cache listing and 1. us "Navigate to" with map or 2. go via compass page and "Show on map"

### Reproducible

Yes

### c:geo Version

2025.09.04-NB-4e5dec7

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #17396, fix #17395: fix edge-2-edge glitches within map and wherigo status bar

### CODE REVIEW

File: main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java [hunk 1]
```diff
@@ -60,28 +60,12 @@ public static boolean toggleActionBar(@NonNull final AbstractActionBarActivity a
...
     private static void showActionBarSpacer(@NonNull final Activity activity, final boolean showSpacer) {
-        if (Settings.getMapActionbarAutohide()) {
-            activity.findViewById(R.id.actionBarSpacer).setVisibility(showSpacer ? View.VISIBLE : View.GONE);
-        }
+        activity.findViewById(R.id.actionBarSpacer).setVisibility(showSpacer ? View.VISIBLE : View.GONE);
     }
 
     private static void setStableLayout(@NonNull final AbstractNavigationBarActivity activity, final boolean showSpacer) {
-        if (showSpacer && Settings.getMapActionbarAutohide()) {
+        if (showSpacer) {
```
Comment (eddiemuc) [inline main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java:68]: @moving-bits what is the reason for setting the (deprecated) systemuivisibility flag here?

File: main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java [hunk 2]
```diff
@@ -60,28 +60,12 @@ public static boolean toggleActionBar(@NonNull final AbstractActionBarActivity a
         return !isShown;
     }
 
-    private static boolean toggleActionBarHelper(@NonNull final AbstractNavigationBarActivity activity) {
```
Comment (eddiemuc) [inline main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java:63]: this method was unused

File: main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java [hunk 3]
```diff
@@ -234,7 +234,8 @@ protected void onNewIntent(final Intent intent) {
     @Override
     protected Insets calculateInsetsForActivityContent(@NonNull final WindowInsetsCompat windowInsets, @NonNull final Insets def) {
         final Insets insets = super.calculateInsetsForActivityContent(windowInsets, def);
-        if (hideNavigationBar) {
+        if (hideNavigationBar || getSelectedBottomItemId() == MENU_HIDE_NAVIGATIONBAR) {
```
Comment (eddiemuc) [inline main/src/main/java/cgeo/geocaching/activity/AbstractNavigationBarActivity.java:237]: This fixes the bug with overlapping on the BOTTOM of the map

File: main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java [hunk 4]
```diff
@@ -60,28 +60,12 @@ public static boolean toggleActionBar(@NonNull final AbstractActionBarActivity a
...
-            actionBar.show();
-            return true;
-        }
-    }
-
     private static void showActionBarSpacer(@NonNull final Activity activity, final boolean showSpacer) {
-        if (Settings.getMapActionbarAutohide()) {
-            activity.findViewById(R.id.actionBarSpacer).setVisibility(showSpacer ? View.VISIBLE : View.GONE);
-        }
+        activity.findViewById(R.id.actionBarSpacer).setVisibility(showSpacer ? View.VISIBLE : View.GONE);
```
Comment (eddiemuc) [inline main/src/main/java/cgeo/geocaching/utils/HideActionBarUtils.java:64]: Removing the IF fixes the problem with overlapping on the TOP of the map

**Comment by eddiemuc** [comment]
Merge fast to get feedback from nightlies.
