### PR TITLE
fix #17503: Set geocode to get prefilled variable-list for edit waypoint 

### LINKED ISSUE #17503: Empty variable list, when adding new calculated waypoint
### Describe your problem!

If you already have variables defined and you want to add a new calculated waypoint, the variables are empty.

### How to reproduce?

Define variables and fill them with values
Add waypoint
Select calculated coordinates
Add previous defined variable in coordinates field

### Actual result after these steps?

The variable does not show a value

### Expected result after these steps?

The variable should show the prefilled value

### Reproducible

Yes

### c:geo Version

Nightly 

### System information

```text

```

### Additional Information

Screenshots will follow

### PR DESCRIPTION
**Pull request by murggel**
## Description

Set as much coordinate input data as possible in CoordinateInputDialog

## Related issues

fix #17503

### CODE REVIEW

File: main/src/main/java/cgeo/geocaching/ui/dialog/CoordinateInputDialog.java [hunk 1]
```diff
@@ -112,7 +114,7 @@ public static void show(final Context context, final DialogCallback callback, fi
             CoordinatesCalculateGlobalDialog.show(fragmentManager, callback, inputData);
             return;
         }
-        new CoordinateInputDialog(context, callback, CoordinateDialogDisplayModeEnum.Waypoint).show(inputData.getGeopoint());
+        new CoordinateInputDialog(context, callback, CoordinateDialogDisplayModeEnum.Waypoint).show(inputData);
```
Comment (murggel) [inline main/src/main/java/cgeo/geocaching/ui/dialog/CoordinateInputDialog.java:117]: Set as much coordinate input data as possible not only geopoint

**Comment by murggel** [comment]
Ready for review

**Comment by eddiemuc** [comment]
Failing tests seem to be unrelated. Let's try in nightlies
