### PR TITLE
adapt pattern for gc.com trackable owner (fix #9999)

### LINKED ISSUE #9999: tests fail on testSearchTrackable()
Last builds fail due to `testSearchTrackable()` failing on owner name:

```
cgeo.geocaching.CgeoApplicationTest.testSearchTrackable

org.junit.ComparisonFailure: expected:<"blafoo"> but was:<null>
at cgeo.geocaching.CgeoApplicationTest.testSearchTrackable(CgeoApplicationTest.java:78)
at java.lang.reflect.Method.invoke(Native Method)
at junit.framework.TestCase.runTest(TestCase.java:168)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at androidx.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
at junit.framework.TestResult.run(TestResult.java:118)
at androidx.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
at junit.framework.TestCase.run(TestCase.java:124)
at androidx.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at androidx.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:97)
at androidx.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:65)
at androidx.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:115)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
```

Reason found after analyses: HTML source for TB page on gc.ocm has changed. Not sure whether permanently and whether on all their servers.

I'll prepare a fix for this.

### PR DESCRIPTION
**Pull request by moving-bits**

### CODE REVIEW

**Comment by Lineflyer** [comment]
Congratulation to issue/PR number 10000 :)

**Comment by Lineflyer** [comment]
But this should go to `release`.
Already got first support mails, that the TB page does not show anything which I assume is related to this.

**Comment by moving-bits** [comment]
> But this should go to `release`.
> Already got first support mails, that the TB page does not show anything which I assume is related to this.

We do have a beta running on `release`. Do we have to push that aside temporarily, and put this fix here on top of actual currently released version?

**Comment by Lineflyer** [comment]
Usually we don't go this way for such kind of more minor regression. Either we accept releasing with the beta regressions if we prefer a fast fix of this issue here, or users have to be patient until we sorted out the other beta regressions.

Because "fiddling" with the branches is also quite an effort for a relatively minor regression. In fact it seems you can still log them, just it shows no description.

**Comment by moving-bits** [comment]
I'll adapt the PR accordingly so that it can be targeted against `release`.

**Comment by moving-bits** [comment]
retest this please

**Comment by Lineflyer** [comment]
Seems there are more website changes.

**Comment by bekuno** [comment]
See Issue #9150.
Maybe this should also be prepared for PATTERN_OWNER_GUID and PATTERN_TRACKABLE_SPOTTEDUSER.
(Do we test these values?)

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
> 
> 
> See Issue #9150.
> Maybe this should also be prepared for PATTERN_OWNER_GUID and PATTERN_TRACKABLE_SPOTTEDUSER.
> (Do we test these values?)

Thats the currently failing tests.

**Comment by moving-bits** [comment]
> Seems there are more website changes.

I'll look into this tonight.

File: main/src/cgeo/geocaching/connector/gc/GCParser.java [hunk 1]
```diff
@@ -1410,10 +1410,17 @@ static Trackable parseTrackable(final String page, final String possibleTracking
...
-            if (matcherOwner.find()) {
-                trackable.setOwnerGuid(matcherOwner.group(1));
-                trackable.setOwner(matcherOwner.group(2).trim());
+            final MatcherWrapper matcherOwnerNew = new MatcherWrapper(GCConstants.PATTERN_TRACKABLE_OWNER_NEW, page);
+            if (matcherOwnerNew.find()) {
+                trackable.setOwnerGuid(matcherOwnerNew.group(1));
+                trackable.setOwner(matcherOwnerNew.group(2).trim());
+
+            } else {
+                final MatcherWrapper matcherOwner = new MatcherWrapper(GCConstants.PATTERN_TRACKABLE_OWNER, page);
```
Comment (fm-sys) [inline main/src/cgeo/geocaching/connector/gc/GCParser.java:1419]: Do we need this fallback? From my testings the profile URLs were changed for all Trackables/Caches in one step. So no need for if/else which increases code complexity...

Comment (fm-sys) [reply main/src/cgeo/geocaching/connector/gc/GCParser.java:1419]: And even if needed, it could be combined with `https?://www.geocaching.com/p(rofile)?/` (attention: in this way this will change the group indexes)

Comment (moving-bits) [reply main/src/cgeo/geocaching/connector/gc/GCParser.java:1419]: Yeah, thought the same after reading your first comment. Not sure whether the change is rolled out completely yet, but with the adapted pattern we are on the safe side.
