### PR TITLE
Fix #8589: Make coordinate parsing more strict

### LINKED ISSUE #8589: Wrongly parsed coords from user note
From support mail for version 2020.07.02

Using this in your personal note results in three waypoints being automatically created:
```
Answer questions
6, 12, 16, 29, 54, 3, 36, 5, 3, 47, 45, 43
```

---

I informed the user that he can turn this feature of for this particular cache, however we should analyze if this can be optimized without any disadvantages while parsing.

### PR DESCRIPTION
**Pull request by UniQP**
We now forbid all special characters of the coordinates to occur between the coordinate parts.

### CODE REVIEW

**Comment by Lineflyer** [comment]
Not sure if we should really exclude things like having a separator ( e.g. / or -) between N and E.

**Comment by bekuno** [comment]
We should also build some negative tests. 
This meens to test strings which not should end in coords. (like the problem from #8589)

**Comment by UniQP** [comment]
Changed the PR to exclude only some characters between the coordinate parts. Also added some negative tests as requested by @bekuno.

**Comment by Lineflyer** [comment]
@bekuno @moving-bits 
Please feel free to review and merge if OK.

File: tests/src/cgeo/geocaching/location/GeoPointParserTest.java [hunk 1]
```diff
@@ -313,4 +308,23 @@ public void test6802() {
...
     }
 
+    @Test
+    public void test8078() {
+        try {
+            GeopointParser.parse("2.2.3.8");
+            failBecauseExceptionWasNotThrown(Geopoint.ParseException.class);
+        } catch (final Geopoint.ParseException e) {
+            // expected
+        }
```
Comment (bekuno) [inline tests/src/cgeo/geocaching/location/GeoPointParserTest.java:318]: this can be replaced by 
`        assertParsingFails("2.2.3.8"); `

File: tests/src/cgeo/geocaching/location/GeoPointParserTest.java [hunk 2]
```diff
@@ -313,4 +308,23 @@ public void test6802() {
...
+    }
+
+    @Test
+    public void test8589() {
+        try {
+            GeopointParser.parse("6, 12, 16, 29");
+            failBecauseExceptionWasNotThrown(Geopoint.ParseException.class);
+        } catch (final Geopoint.ParseException e) {
+            // expected
+        }
```
Comment (bekuno) [inline tests/src/cgeo/geocaching/location/GeoPointParserTest.java:328]: this can be replaced by
assertParsingFails("6, 12, 16, 29");

File: tests/src/cgeo/geocaching/location/GeoPointParserTest.java (hunk 1 above)
Comment (UniQP) [reply tests/src/cgeo/geocaching/location/GeoPointParserTest.java]: Done.

File: tests/src/cgeo/geocaching/location/GeoPointParserTest.java (hunk 2 above)
Comment (UniQP) [reply tests/src/cgeo/geocaching/location/GeoPointParserTest.java]: Done.

**Comment by moving-bits** [comment]
retest this please

**Comment by baiti** [comment]
> We now forbid all special characters of the coordinates to occur between the coordinate parts.

This is not good. The waypoint dialog's coorindate entry pull down provides a function to take coordinates from the clipboard. A very popular application that can put coordinates into the clipboard is Locus Map, however, Locus Map uses the format:

Nxx° yy.zzz', Exx° yy.zzz'

This format was parsed by c'geo correctly until the referenced change was made. Now since the colon between Lat / Lon part makes the parser  reject these coordinates, the effect is that the menu entry "Use coords from clipboard" is not even displayed anymore.

**Review by baiti — COMMENTED** [review]
This change breaks coordinate parsing when coordinates come from Locus Map via the clipboard. Please backout this change. Coordinates in the form of "Nxx° yy.zzz', Exx° yy.zzz'" should be parsed corrextly as valid coordinates. The only other option I see is to convince the Locus Map folks to remove that colon as it is "ugly" in the first place and doesn't really make sense, however, as a matter of fact, that colon happens to be there since a very long time and  c'geo was indeed able to process it correctly

**Comment by moving-bits** [comment]
@baiti 
Thanks for your feedback. I have created a new issue for this for easier tracking. (It's hard to track things in issues already closed.)
