### PR TITLE
fix #17305: "Did not find" status not handled correctly for Opencachi…

### LINKED ISSUE #17305: "Did not find" status not handled correctly for Opencaching
### Describe your problem!

When a cache is marked as "Did not find" (DNF) on the Opencaching network, the status is not always correctly displayed in c:geo.

### How to reproduce?

**Case 1**: Log DNF on website
- Log a cache as DNF on the Opencaching website.
- Refresh the cache in the app.

Observed:
- Log is shown with correct username.
- Cache details page does not show “Status: DNF”.
- DNF icon (sad blue face) is missing.
- Filters for DNF do not work.

---

**Case 2**: Log DNF in app, then data expires
- Log a cache as DNF in the app.
- Everything works at first (icon, filtering, etc.).
- Delete orphaned data or wait until cache expires (72h).

Observed:
- Same issues as in Case 1.

### Actual result after these steps?

Cache is logged, but Status is missing.

### Expected result after these steps?

Status of the cache should reflect what is on the Opencaching website.

### Reproducible

Yes

### c:geo Version

2025.08.05

### System information

```text
## System information

c:geo version: 2025.08.05

Datetime: 15 August at 16:30

Device:
-------
- Device type: ASUS_AI2302 (EU_AI2302, asus)
- Available processors: 8
- Android version: 15
- Android build: AQ3A.240812.002.35.0604.0404.131 release-keys
- Screen resolution: 1080x2400px (393x807dp)
- Pixel density: 2.75
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 25.30.31 (260400-786424874)
- Memory:  Available:7.8 GB, Total:14.9 GB, Threshold: 300.0 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v10, Count:137
- Set language: en_GB (system default)
- System date format: dd/MM/y
- Time zone: GMT+02:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: never
- Last auto backup: 2 Aug, 08:07
- Routing mode: Walk (shortest.brf / trekking.brf / car-eco.brf / (none) / (none))
- Map mode: UnifiedMap / live / OSM multi-threading: off
- Map: OpenStreetMap.org
  - Id: cgeo.geocaching.unifiedmap.tileproviders.OsmOrgSource:null
  - Attrs: © OpenStreetMap contributors
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: Status: 3 items ({"advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"status","config":{"values":["found_no","exclude_disabled","exclude_archived"]}}]}})
- OFFLINE: None ({"advanced":false,"inconclusive":false})

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Login OK) / PREMIUM
   - Geocaching.com Adventure Lab
   - opencache.uk: Logged in (Login OK)
   - opencaching.pl: Logged in (Login OK)
   - Internal
- Geocaching.com date format: dd/MM/yyyy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: Communication error //  (2025-08-13 18-42)
- Last successful login on geocaching.com: 2025-08-15 16-29
- Routing: internal / BRouter installed: false

Permissions
-------
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: DENIED
- WRITE_EXTERNAL_STORAGE: DENIED
- POST_NOTIFICATIONS: granted

Wherigo
-------
- playing:false, debug:false, debugFC:false
- Name: - (unknown)
- Cache context: null
- Last Error: null
- Last Played: null / null
- Visible things: LOCATION:0, ITEM:0, INVENTORY:0, TASK:0, THING:0
- Cartridge File: null
- Load Slots: 

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (393.2 GB free) v3 internal isDir(10 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (393.2 GB free) v3 internal isDir(10 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (393.2 GB free) v3 external non-removable isDir(12 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (393.2 GB free) v3 internal isDir(0 entries)
- Map render theme path: 
- Public Folders: #14
  - BASE: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo (av:true, files:>=10, size:>=2.8 GB, free:>=393.2 GB)
  - OFFLINE_MAPS: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/maps (av:true, files:>=9, size:>=2.8 GB, free:>=393.2 GB)
  - OFFLINE_MAP_THEMES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/maps/_themes (av:true, files:>=4, size:>=867.8 KB, free:>=393.2 GB)
  - OFFLINE_MAP_SHADING: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/maps/_hgt (av:true, files:>=0, size:>=0 B, free:>=393.2 GB)
  - BACKGROUND_MAPS: file:///storage/emulated/0/Android/media/cgeo.geocaching (av:true, files:>=0, size:>=0 B, free:>=393.2 GB)
  - LOGFILES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/logfiles (av:true, files:>=1, size:>=9.3 KB, free:>=393.2 GB)
  - GPX: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/gpx (av:true, files:>=0, size:>=0 B, free:>=393.2 GB)
  - BACKUP: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/backup (av:true, files:>=4, size:>=2.0 MB, free:>=393.2 GB)
  - FIELD_NOTES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/field-notes (av:true, files:>=0, size:>=0 B, free:>=393.2 GB)
  - SPOILER_IMAGES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/GeocachePhotos (av:true, files:>=0, size:>=0 B, free:>=393.2 GB)
  - ROUTING_BASE: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/routing (av:true, files:>=11, size:>=227.5 MB, free:>=393.2 GB)
  - ROUTING_TILES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/routing/segments4 (av:true, files:>=3, size:>=227.4 MB, free:>=393.2 GB)
  - WHERIGO: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/wherigo (av:true, files:>=9, size:>=5.2 MB, free:>=393.2 GB)
  - TEST_FOLDER: file:///data/user/0/cgeo.geocaching/files/unittest (av:true, files:>=0, size:>=0 B, free:>=393.2 GB)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary:cgeo (6 Nov 2024, 20:52):RW

Database
-------
- File: /data/user/0/cgeo.geocaching/databases/data (v106, Size:452.0 KB) on system internal storage
- Data: {cg_attributes=82, cg_caches=11, cg_caches_lists=8, cg_categories=0, cg_extension=14, cg_filters=0, cg_lists=1, cg_logCount=58, cg_logImages=61, cg_logs=426, cg_logs_offline=0, cg_logs_offline_images=0, cg_logs_offline_trackables=0, cg_route=0, cg_search_destination_history=0, cg_spoilers=19, cg_trackables=1, cg_trail_history=700, cg_variables=0, cg_waypoints=10}
- Extension Data: {DBEXTENSION_DOWNGRADEABLE_DBVERSION=1, DBEXTENSION_FOUNDNUM=3, DBEXTENSION_LAST_TRACKABLE_ACTION=6, DBEXTENSION_ONE_TIME_DIALOGS=4}

--- End of system information ---
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by baiti**
OKAPI's is_not_found field was never requested or parsed — parseCoreCache() only called setFound() from is_found, leaving setDNF() never invoked. This caused the DNF icon, status display, and filters to silently fail after refreshing an Opencaching cache.

Changes in OkapiClient.java
New constant: CACHE_IS_NOT_FOUND = "is_not_found"
SERVICE_CACHE_CORE_L3_FIELDS: added is_not_found so the field is requested from the OKAPI API
parseCoreCache(): parse is_not_found and call cache.setDNF() accordingly
parseCache(): extend visited-date fetch to also trigger on isDNF(), not just isFound()
getCacheFoundDate(): include LogType.DIDNT_FIND_IT in the log-type check; replace raw id comparisons (id == 2 || id == 10) with enum references (LogType.FOUND_IT, LogType.ATTENDED, LogType.DIDNT_FIND_IT)

### CODE REVIEW

**Comment by baiti** [comment]
Co-pilot reviewed, made quite a few suggestsions and offered to "implement all suggestions". I checked with claude (as he helped with coding) and here is what he says:

❯ the web-ui, when looking at the PR offers me to "implement all suggestsions", can and should I do this?

⏺ No, don't use it. Here's why:

  - Suggestion #2 (parseCoreCache mutual exclusivity) — we already implemented exactly that logic, so GitHub would detect the suggestion as outdated/conflicting.
  - Suggestion #1 (getCacheFoundDate) — Copilot's suggested fix is simpler but worse than what we implemented. Copilot suggested just removing DIDNT_FIND_IT entirely:
  if (log.logType == LogType.FOUND_IT || log.logType == LogType.ATTENDED) {
  - That breaks DNF visited-date tracking — DNF caches would call the method and find nothing. Our fix passes isDNF so each case matches the right log type. Applying
  Copilot's suggestion would silently regress that behavior.

  The fixes we already pushed are strictly better than what the web UI would apply. Leave them as-is.

So this tells a clear story: The two AI agents are not in agreement ;)

I go w/ Claude for now ...

**Comment by bekuno** [comment]
retest this please

File: main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java [hunk 1]
```diff
@@ -886,8 +888,24 @@ private static void parseCoreCache(final ObjectNode response, @NonNull final Geo
         final String country = response.get(CACHE_COUNTRY) == null ? null : response.get(CACHE_COUNTRY).asText();
         cache.setLocation(region == null ? country : (country == null ? region : region + ", " + country));
 
-        if (response.has(CACHE_IS_FOUND)) {
-            cache.setFound(response.get(CACHE_IS_FOUND).asBoolean());
+        final boolean hasFound = response.has(CACHE_IS_FOUND);
```
Comment (eddiemuc) [inline main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java]: I don't quite understand why the logix gets so much more complex. There seems to be more than just differentiation between dnf and found now. Especially differentiation between isFound and hasFound, what's the difference?

File: main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java [hunk 2]
```diff
@@ -250,7 +251,7 @@ static void markOwnAndOwnerLogs(final Geocache cache, final List<LogEntry> parse
     }
 
     @WorkerThread
-    public static long getCacheFoundDate(final String geoCode) {
+    public static long getCacheFoundDate(final String geoCode, final boolean isDNF) {
```
Comment (eddiemuc) [inline main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java]: Seems weird to pass isDNF as parameter.
It seems that fhis function searchds through the logs to find either the first find or the first dnf log. What happens when a user logs both a dnf and then later a find?

File: main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java (hunk 1 above)
Comment (baiti) [reply main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java]: > I don't quite understand why the logix gets so much more complex. There seems to be more than just differentiation between dnf and found now. Especially differentiation between isFound and hasFound, what's the difference?

`hasFound/isFound` complexity: Both `is_found` and `is_not_found` are always requested together (`SERVICE_CACHE_CORE_L3_FIELDS`), so they're either both present or
both absent. We don't need to separately track "field present but false" vs "field absent" for each
independently. The Copilot-suggested logic over-engineered this, I should not have followed its suggestion. Simplification:
```
if (response.has(CACHE_IS_FOUND)) {
     final boolean isFound = response.get(CACHE_IS_FOUND).asBoolean();
     cache.setFound(isFound);
     cache.setDNF(!isFound && response.has(CACHE_IS_NOT_FOUND) &&
     response.get(CACHE_IS_NOT_FOUND).asBoolean());
}
```

Will fix this right away

File: main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java (hunk 2 above)
Comment (baiti) [reply main/src/main/java/cgeo/geocaching/connector/oc/OkapiClient.java]: > Seems weird to pass isDNF as parameter. It seems that fhis function searchds through the logs to find either the first find or the first dnf log. What happens when a user logs both a dnf and then later a find?

`isDNF` parameter: OKAPI's `latest_logs` are reverse-chronological (most recent first) with
`user_logs_only=true`. The most recent log of `FOUND_IT / ATTENDED / DIDNT_FIND_IT` will always match the cache's current state — because that same log is what determined `is_found/is_not_found` on OKAPI's side. So for your scenario ("DNF then later a find"): logs = [FOUND_IT, DIDNT_FIND_IT], first match = FOUND_IT, correct date. No `isDNF` parameter needed.

Will fix t his too.

**Comment by bekuno** [comment]
retest this please

**Comment by moving-bits** [comment]
@baiti / @eddiemuc 
Is this PR ready to merge?

**Comment by baiti** [comment]
> @baiti / @eddiemuc Is this PR ready to merge?

Yes, from my perspective it is. I have worked @edddiemuc's review findings.

**Comment by eddiemuc** [comment]
Lgtm, let's merge.

Happy Easter 🐣
