### PR TITLE
align margins and optimize out of sync dialog 

### LINKED ISSUE #13883: Inconsistent margins
### Describe your problem!

Some buttons in cgeo are not properly aligned and use inconsistent margins. 

### How to reproduce?

Open cache and create out of sync variable

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Yes

### c:geo Version

2023.01.16

### System information

_No response_

### Additional Information

Screenshot_20230116_093419_cgeo geocaching_edit_339809508401273
Screenshot_20230116_093331_cgeo geocaching_edit_339677364949209

### PR DESCRIPTION
**Pull request by fm-sys**
fix #13883

setting as draft, as I couldn't test my PR cause of #14011

### CODE REVIEW

**Comment by fm-sys** [comment]
grafik

File: main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java [hunk 1]
```diff
@@ -218,6 +219,22 @@ private void applyCommons(final AlertDialog.Builder builder) {
         }
     }
 
+    private void applyCommonsForSelectionDialogs(final AlertDialog.Builder builder) {
+        // By default message is not supported if a listview is shown, therefore we need to build the dialog ourselves and set it as header
+        if (message != null || title != null) {
```
Comment (eddiemuc) [inline main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java:224]: Wouldn't it be enough to apply the custom header if message != null? Setting a custom title (without message) is also supported for selection dialog w/o custom header.

Comment (fm-sys) [reply main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java:224]: Yes in principle, although this would slightly increase complexity cause we would need to set the title in two different ways depending on whether message != null.

Do you have a preference?

Comment (eddiemuc) [reply main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java:224]: I would call applyCommons in case message is null.

Anyway, current implementation is fine too.

Comment (fm-sys) [reply main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java:224]: Ok, will change it...
