### PR TITLE
fix #6388: silently discard tasks when shutting down executor

### LINKED ISSUE #6388: RejectedExecutionException
From Google Play for beta version 2017.02.28-RC:

User message:
Clicking on icons on the map

Samsung S7 with Android 7.0

```
io.reactivex.exceptions.UndeliverableException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@50077de rejected from java.util.concurrent.ScheduledThreadPoolExecutor@d71ec00[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 12]
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:134)
	at io.reactivex.internal.schedulers.NewThreadWorker.schedule(NewThreadWorker.java:51)
	at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:400)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@50077de rejected from java.util.concurrent.ScheduledThreadPoolExecutor@d71ec00[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 12]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2049)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:814)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:305)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:550)
	at io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:127)
	... 9 more
```

### PR DESCRIPTION
**Pull request by samueltardieu**
This will work only for executors that we do control explicitly,
such as the network and the refresh executors.

### CODE REVIEW

File: main/src/cgeo/geocaching/utils/AndroidRxUtils.java [hunk 1]
```diff
@@ -129,4 +134,17 @@ public void run() {
             }
         });
     }
+
+    /**
+     * Provide an executor service which a fixed number of threads and an unbounded queue. If the
```
Comment (UniQP) [inline main/src/cgeo/geocaching/utils/AndroidRxUtils.java]: There's a typo in the first sentence: s/which/with/ or s/which/that has/.

Comment (samueltardieu) [inline main/src/cgeo/geocaching/utils/AndroidRxUtils.java]: Thanks :)
