### PR TITLE
Fix #17768 - Add GSAK corrected lat and long

### LINKED ISSUE #17768: gpx export of cache with corrected coords does not contain gsak:wptExtension/gsak:LatBeforeCorrect
### Describe your problem!

A GPX export of a cache with corrected coords does not (no longer) contain gsak:wptExtension/gsak:LatBeforeCorrect in the GPX file. 
Importing such a file in GSAK or other Locus will not show the cache with corrected coordinates. 

In https://github.com/cgeo/cgeo/issues/13108#issuecomment-1176418749 ztNFny wrote: 

> c:geo, gsak, Locus all support gsak:wptExtension/gsak:GcNote for "Personal Cache Note" and set gsak:wptExtension/gsak:LatBeforeCorrect if coords are corrected.

This seems no longer be the case and causes trouble / incorrect results when such a gpx file is imported in other programs. 

### How to reproduce?

Open a cache with corrected coordinates in cgeo and export it as GPX, check the GPX file for "LatBeforeCorrect" which should be present, but isn't. 

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Yes

### c:geo Version

2026.01.02

### System information

```text

```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ReggieDoodle**
## Description
Adds two missing fields to the GSAK section of an exported GPX file containing the original coordinates

## Related issues
Bug #17768  (though actually a feature request as it was missing functionality)

## Additional context
Tested locally by importing a new GPX file to GSAK and checking that the user corrected flag is set where appropriate

No unit tests have been changed (or hopefully affected)

### CODE REVIEW

**Comment by eddiemuc** [comment]
> Can one of the core team members give me the the permission to test this?

Ok to test

**Comment by eddiemuc** [comment]
@ReggieDoodle change should go to release instead of master imho. I too think it is a bug.

**Comment by ReggieDoodle** [comment]
Sorry, confusion here - bugs to release, feature requests to master for future inclusion but I believe this is a feature request - the functionality was missing - but if you want it in release can you cherry pick it once approved ?

Tks

File: main/src/main/java/cgeo/geocaching/export/GpxSerializer.java [hunk 1]
```diff
@@ -210,6 +211,22 @@ private void writeGsakExtensions(@NonNull final Geocache cache) throws IOExcepti
                 }
             }
         }
+        if (cache.hasUserModifiedCoords()) {
+            if (cache.hasWaypoints()) {
```
Comment (murggel) [inline main/src/main/java/cgeo/geocaching/export/GpxSerializer.java]: You could use the method `cache.getOriginalWaypoint()` instead of looking yourself for the waypoint

**Comment by ReggieDoodle** [comment]
@murggel 
I was just going on your advice in the original ticket "_So checking the flag and using the coords of the waypoint of type WaypointType.ORIGINAL for export would be a good option IMHO._" Now had you pointed out there was already a helper method I would have of course used it, but hey, at least I know a bit more about waypoints now ;-)

I'll make the change next time I'm on the PC

Dave

**Comment by moving-bits** [comment]
@ReggieDoodle 
Thanks for your contribution, very welcomed!
