### PR TITLE
show character counter starting from 3000 characters

### LINKED ISSUE #7390: Log posting with max text length fails
##### Detailed steps causing the problem:
- Compose a log for a gc.com cache
- Enter as much text as possible as log text (until no further characters are accepted)
- Try to send the log online

##### Actual behavior after performing these steps:
Logging immediately fails with the corresponding c:geo failure window.
No long posted online.

##### Expected behavior after performing these steps:
Max characters allowed for log in c:geo seems not to match what gc.com supports (I assume).
As soon as I reduce the log text by four characters the logging works smooth.

##### Version of c:geo used:
2019.03.17-RC (current `release` branch)

##### Is the problem reproducible for you?
Yes

##### System information:
Android 5.0.1, Samsung Galaxy S4

##### Other comments and remarks:
Seems **not** related to recent logging change #7388

### PR DESCRIPTION
**Pull request by fm-sys**
fix #7390

### CODE REVIEW

File: main/src/cgeo/geocaching/log/LogCacheActivity.java [hunk 1]
```diff
@@ -74,6 +80,7 @@
 public class LogCacheActivity extends AbstractLoggingActivity {
 
     private static final String SAVED_STATE_LOGENTRY = "cgeo.geocaching.saved_state_logentry";
+    private static final int LOG_MAX_LENGHT = 4000;
```
Comment (moving-bits) [inline main/src/cgeo/geocaching/log/LogCacheActivity.java:83]: typo: LOG_MAX_LENGTH

Comment (fm-sys) [reply main/src/cgeo/geocaching/log/LogCacheActivity.java]: Thanks for spotting it, fixed!
