### PR TITLE
Fix #17882: restore long click on enable live

### LINKED ISSUE #17882: [Nightly] Long click on "Live-Mode" does not work any more
### Describe your problem!

UnifiedMap: Long click on "Enable Live" does not work as before 

### How to reproduce?

Select a list
Open Map for the list
Long click on "enable live"

### Actual result after these steps?

Tooltip is shown

### Expected result after these steps?

All offline stored caches should be displayed (see PR #16753)

### Reproducible

Yes

### c:geo Version

2026.02.20-NB-29e4aeb

### System information

```text

```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by murggel**
## Description

Restore behaviour of long click on enable live, old implementation probably does not work with new toolbar (PR #17775) -> move it into post-handler (see working menu_select_mapview)

## Related issues

Fix #17882
rel #16753
rel #16360

### CODE REVIEW

File: main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java [hunk 1]
```diff
@@ -1504,6 +1494,17 @@ private void initializeMapViewLongClick() {
...
                 });
             }
+
+            final View liveButton = findViewById(R.id.menu_map_live);
+            if (liveButton != null) {
+                liveButton.setOnLongClickListener(v -> {
+                    // viewModel.mapType = UnifiedMapType.getPlainMapWithTarget(viewModel.mapType); // switch to PLAIN mode
+                    //  viewModel.transientIsLiveEnabled.setValue(false);
+                    Settings.setLiveMap(false);
+                    // reloadCachesAndWaypoints();
```
Comment (moving-bits) [inline main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java]: This will change c:geo's behavior on long-tapping the button:

While the old behavior only _temporarily_ switches to showing all stored caches without enabling live mode, the new behavior would disable live mode.

Also: Will just disabling live mode (which might not have been enabled at that point at all) lead to reloading the stored caches?

IIRC, the main use case for long-tapping on "enable/disable live mode" button was this:
- Map a stored list
  - This shows a map without live map, displays only caches from the selected list
- If you then want to add all stored caches, without enabling live mode, you can do so by long-tapping that button

I cannot test the PR currently, but from looking at the code I think this won't work any more with this PR.

Comment (murggel) [reply main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java]: Sorry, I missed to uncomment the code again, that was just for testing purpose if the code would be reached...

Will change it as soon as I have access to my computer.

Comment (murggel) [inline main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java]:
```suggestion
                    viewModel.mapType = UnifiedMapType.getPlainMapWithTarget(viewModel.mapType); // switch to PLAIN mode
                    viewModel.transientIsLiveEnabled.setValue(false);
                    Settings.setLiveMap(false);
                    reloadCachesAndWaypoints();
```

**Comment by moving-bits** [comment]
retest this please
