### PR TITLE
disable check if short description is part of long description

### LINKED ISSUE #11455: OC14726 not showing description
### Describe your problem!

A certain OC cache is not showing any description text in c:geo.
On the website the cache description is visible.

### How to reproduce?

- Be authenticated to OC.de
- Open OC14726
- Swipe to description tab

### Actual result after these steps?

Empty description

### Expected result after these steps?

Description shown

### Reproducible

Yes

### c:geo Version

2021.08.08-RC

### System information

_No response_

### Additional Information

Did not check any deeper, whether this is an existing problem, a OKAPI problem or a beta regression

### PR DESCRIPTION
**Pull request by bekuno**
## Description

Disable the check if short description is part of long description and therefore no removing of short description, if it is contained.
In the previous release the check did not work. Therefore remove for now the check and so both description are shown as before.

The real problem should be solved separately.
Also tests are missing.

## Related issues

fixes #11455

### CODE REVIEW

**Comment by bekuno** [comment]
retest this please

File: main/src/cgeo/geocaching/CacheDetailActivity.java [hunk 1]
```diff
@@ -1835,7 +1835,8 @@ private void loadDescription(final CacheDetailActivity activity, final String de
                     descriptionView.setMovementMethod(AnchorAwareLinkMovementMethod.getInstance());
                     descriptionView.setVisibility(View.VISIBLE);
                     activity.addContextMenu(descriptionView);
-                    activity.potentiallyHideShortDescription();
+                    // TODO fix the non working method, see https://github.com/cgeo/cgeo/issues/11455
+                    //activity.potentiallyHideShortDescription();
```
Comment (moving-bits) [inline main/src/cgeo/geocaching/CacheDetailActivity.java:1839]: I propose to remove the method `potentiallyHideShortDescription` as well, as the commented-out line is the only place calling this non-functional method.

**Review by moving-bits — CHANGES_REQUESTED** [review]

File: main/src/cgeo/geocaching/CacheDetailActivity.java (hunk 1 above)
Comment (bekuno) [reply main/src/cgeo/geocaching/CacheDetailActivity.java:1839]: I just disabled the call and left the method as it is to fix the problem later.
For this point I created Issue #11464.

Comment (bekuno) [reply main/src/cgeo/geocaching/CacheDetailActivity.java:1839]: I deactivated the called method now.

**Comment by bekuno** [comment]
Retest this please

Once more a CI build test with error but at and success.
~~~
09:41:49  FAILURE: Build failed with an exception.
09:41:49  
09:41:49  * What went wrong:
09:41:49  Execution failed for task ':main:installBasicDebug'.
09:41:49  > java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Unknown failure: cmd: Can't find service: package
...
09:41:49  BUILD FAILED in 6m 30s
...
09:42:03  Finished: SUCCESS
~~~

**Comment by bekuno** [comment]
retest this please

**Comment by fm-sys** [comment]
LGTM, let's merge...
