### PR TITLE
fix #13683: Show generated waypoints on map

### LINKED ISSUE #13683: [Nightly] Generated waypoints are not shown on map
### Describe your problem!

The "preview" for generating waypoints from variables does not show them on the map.

### How to reproduce?

Create waypoint with formula
Enter range for some variables
Open coordinates field of the waypoint
Select "generate waypoints" - dialog opens
Select all waypoints and select "show on map"

### Actual result after these steps?

No waypoints are shown

### Expected result after these steps?

The selected waypoints should be shown on the map

### Reproducible

Yes

### c:geo Version

2022.11.16-NB-c66e387

### System information

```text
## System information

c:geo version: 2022.11.16-NB-c66e387

Device:
-------
- Device type: SM-G980F (x1sxx, samsung)
- Available processors: 8
- Android version: 11
- Android build: RP1A.200720.012.G980FXXSCDUJ5
- Screen resolution: 1080x2178px (360x726dp)
- Pixel density: 3.3000002
- System font scale: 1.1 / used scale: 1.1
- Sailfish OS detected: false
- Google Play services: enabled - 22.44.17 (150408-488410709)

Sensor and location:
-------
- Low power mode: active
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:180
- Set language: de
- System date format: dd.MM.yy
- Time zone: GMT+01:00
- Debug mode active: no
- Last backup: 26. Apr., 22:11
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Germany (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:3438-3261:CGeo/maps/germany.map
  - Atts: Map data (c) OpenStreetMap contributors
  - Theme: Elevate.zip:Elevate.xml

Filters:
-------
- Hide waypoints: original visited
- LIVE: _Tour* ([_Tour:inconclusive=false:advanced=true]AND(status:exclude_disabled:exclude_archived))
- OFFLINE: Keine ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))

Stored Filters (#15):
- _Standard: [_Standard:inconclusive=false:advanced=false]AND(status:found_no:exclude_archived))
- _Test: [_Test:inconclusive=false:advanced=true]AND(difficulty_terrain:d=1.5:d=4.0:t=-:t=3.0))
- _toSolve: [_toSolve:inconclusive=false:advanced=true]AND(type:MYSTERY;status:solved_mystery_no))
- _Tour: [_Tour:inconclusive=false:advanced=false]AND(status:found_no:has_offline_found_log_no:solved_mystery_yes:exclude_disabled:exclude_archived))
- _unsaved: [_unsaved:inconclusive=false:advanced=false]AND(status:found_no:exclude_archived;stored_since:-10:-10))
- Events: [Events:inconclusive=false:advanced=false]AND(hidden:2021-09-21:-:false:-1:-1;type:EVENT))
- hasTrackable: [hasTrackable:inconclusive=false:advanced=true]AND(status:has_trackable_yes))
- LabStation: [LabStation:inconclusive=false:advanced=false]AND(note::is_present;type:USER_DEFINED:ADVLAB;status))
- Offlinelog: [Offlinelog:inconclusive=false:advanced=true]AND(status:has_offline_found_log_yes))
- Steffen: [Steffen:inconclusive=false:advanced=true]AND(status:found_no:has_offline_found_log_no;stored_list:122:31))
- toLog_Bianca: [toLog_Bianca:inconclusive=false:advanced=false]AND(stored_list:86;status:found_yes;log_entry:biansch :contains:inverse=true:logtext=:logtext=contains))
- toLog_Carolin: [toLog_Carolin:inconclusive=false:advanced=false]AND(stored_list:86;status:found_yes;log_entry:carosch:contains:inverse=true:logtext=:logtext=contains))
- Umlaute: [Umlaute:inconclusive=false:advanced=true]OR(note:+29:contains;note:+28:contains;note:+27:contains))
- winter: [winter:inconclusive=false:advanced=true]AND(attributes:winter_no:inverse=true:attributesources=3))
- WithNotes: [WithNotes:inconclusive=false:advanced=true]AND(note::is_present))

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   Geocaching.com Adventure Lab
   opencaching.de: Logged in (Anmeldung OK)
- Geocaching.com date format: dd MMM yy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2022-11-15 15-58)
- Last successful login on geocaching.com: 2022-11-18 13-15
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (68,0 GB free) v3 internal isDir(8 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (68,0 GB free) v3 internal isDir(8 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (68,0 GB free) v3 external non-removable isDir(1748 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (68,0 GB free) v3 internal isDir(0 entries)
- Public Folders: #12
  - BASE: SD-Karte/CGeo (User-Defined)[SD-Karte/CGeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo, Av:true, files:>=21, dirs:>=9, totalFileSize:>=6,7 GB, free space: 100,1 GB, files on device: 0)
  - OFFLINE_MAPS: SD-Karte/CGeo/maps (Default)[SD-Karte/CGeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fmaps, Av:true, files:10, dirs:2, totalFileSize:6,7 GB, free space: 100,1 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: SD-Karte/CGeo/maps/_themes (Default)[SD-Karte/CGeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fmaps%2F_themes, Av:true, files:2, dirs:0, totalFileSize:468,1 KB, free space: 100,1 GB, files on device: 0)
  - OFFLINE_MAP_SHADING: SD-Karte/CGeo/maps/_hgt (Default)[SD-Karte/CGeo/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/maps/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 100,1 GB, files on device: 0)
  - LOGFILES: SD-Karte/CGeo/logfiles (Default)[SD-Karte/CGeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:72,7 KB, free space: 100,1 GB, files on device: 0)
  - GPX: SD-Karte/CGeo/gpx (Default)[SD-Karte/CGeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fgpx, Av:true, files:10, dirs:0, totalFileSize:76,4 MB, free space: 100,1 GB, files on device: 0)
  - BACKUP: SD-Karte/CGeo/backup (Default)[SD-Karte/CGeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fbackup, Av:true, files:>=10, dirs:>=10, totalFileSize:>=253,8 MB, free space: 100,1 GB, files on device: 0)
  - FIELD_NOTES: SD-Karte/CGeo/field-notes (Default)[SD-Karte/CGeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Ffield-notes, Av:true, files:4, dirs:0, totalFileSize:8,4 KB, free space: 100,1 GB, files on device: 0)
  - SPOILER_IMAGES: SD-Karte/CGeo/GeocachePhotos (Default)[SD-Karte/CGeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2FGeocachePhotos, Av:true, files:>=2, dirs:>=37, totalFileSize:>=5,2 MB, free space: 100,1 GB, files on device: 0)
  - ROUTING_BASE: SD-Karte/CGeo/routing (Default)[SD-Karte/CGeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Frouting, Av:true, files:9, dirs:1, totalFileSize:340,3 MB, free space: 100,1 GB, files on device: 0)
  - ROUTING_TILES: SD-Karte/CGeo/routing/segments4 (Default)[SD-Karte/CGeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Frouting%2Fsegments4, Av:true, files:2, dirs:0, totalFileSize:340,2 MB, free space: 100,1 GB, files on device: 0)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 68,0 GB, files on device: -1)
- Map render theme path: Elevate.zip:Elevate.xml
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo (1. Apr., 19:00):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:99,2 MB) on system internal storage

--- End of system information ---
## System information

c:geo version: 2022.11.16-NB-c66e387

Device:
-------
- Device type: SM-G980F (x1sxx, samsung)
- Available processors: 8
- Android version: 11
- Android build: RP1A.200720.012.G980FXXSCDUJ5
- Screen resolution: 1080x2178px (360x726dp)
- Pixel density: 3.3000002
- System font scale: 1.1 / used scale: 1.1
- Sailfish OS detected: false
- Google Play services: enabled - 22.44.17 (150408-488410709)

Sensor and location:
-------
- Low power mode: active
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:180
- Set language: de
- System date format: dd.MM.yy
- Time zone: GMT+01:00
- Debug mode active: no
- Last backup: 26. Apr., 22:11
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Germany (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:3438-3261:CGeo/maps/germany.map
  - Atts: Map data (c) OpenStreetMap contributors
  - Theme: Elevate.zip:Elevate.xml

Filters:
-------
- Hide waypoints: original visited
- LIVE: _Tour* ([_Tour:inconclusive=false:advanced=true]AND(status:exclude_disabled:exclude_archived))
- OFFLINE: Keine ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))

Stored Filters (#15):
- _Standard: [_Standard:inconclusive=false:advanced=false]AND(status:found_no:exclude_archived))
- _Test: [_Test:inconclusive=false:advanced=true]AND(difficulty_terrain:d=1.5:d=4.0:t=-:t=3.0))
- _toSolve: [_toSolve:inconclusive=false:advanced=true]AND(type:MYSTERY;status:solved_mystery_no))
- _Tour: [_Tour:inconclusive=false:advanced=false]AND(status:found_no:has_offline_found_log_no:solved_mystery_yes:exclude_disabled:exclude_archived))
- _unsaved: [_unsaved:inconclusive=false:advanced=false]AND(status:found_no:exclude_archived;stored_since:-10:-10))
- Events: [Events:inconclusive=false:advanced=false]AND(hidden:2021-09-21:-:false:-1:-1;type:EVENT))
- hasTrackable: [hasTrackable:inconclusive=false:advanced=true]AND(status:has_trackable_yes))
- LabStation: [LabStation:inconclusive=false:advanced=false]AND(note::is_present;type:USER_DEFINED:ADVLAB;status))
- Offlinelog: [Offlinelog:inconclusive=false:advanced=true]AND(status:has_offline_found_log_yes))
- Steffen: [Steffen:inconclusive=false:advanced=true]AND(status:found_no:has_offline_found_log_no;stored_list:122:31))
- toLog_Bianca: [toLog_Bianca:inconclusive=false:advanced=false]AND(stored_list:86;status:found_yes;log_entry:biansch :contains:inverse=true:logtext=:logtext=contains))
- toLog_Carolin: [toLog_Carolin:inconclusive=false:advanced=false]AND(stored_list:86;status:found_yes;log_entry:carosch:contains:inverse=true:logtext=:logtext=contains))
- Umlaute: [Umlaute:inconclusive=false:advanced=true]OR(note:+29:contains;note:+28:contains;note:+27:contains))
- winter: [winter:inconclusive=false:advanced=true]AND(attributes:winter_no:inverse=true:attributesources=3))
- WithNotes: [WithNotes:inconclusive=false:advanced=true]AND(note::is_present))

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   Geocaching.com Adventure Lab
   opencaching.de: Logged in (Anmeldung OK)
- Geocaching.com date format: dd MMM yy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2022-11-15 15-58)
- Last successful login on geocaching.com: 2022-11-18 13-15
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (68,0 GB free) v3 internal isDir(8 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (68,0 GB free) v3 internal isDir(8 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (68,0 GB free) v3 external non-removable isDir(1748 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (68,0 GB free) v3 internal isDir(0 entries)
- Public Folders: #12
  - BASE: SD-Karte/CGeo (User-Defined)[SD-Karte/CGeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo, Av:true, files:>=21, dirs:>=9, totalFileSize:>=6,7 GB, free space: 100,1 GB, files on device: 0)
  - OFFLINE_MAPS: SD-Karte/CGeo/maps (Default)[SD-Karte/CGeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fmaps, Av:true, files:10, dirs:2, totalFileSize:6,7 GB, free space: 100,1 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: SD-Karte/CGeo/maps/_themes (Default)[SD-Karte/CGeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fmaps%2F_themes, Av:true, files:2, dirs:0, totalFileSize:468,1 KB, free space: 100,1 GB, files on device: 0)
  - OFFLINE_MAP_SHADING: SD-Karte/CGeo/maps/_hgt (Default)[SD-Karte/CGeo/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/maps/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 100,1 GB, files on device: 0)
  - LOGFILES: SD-Karte/CGeo/logfiles (Default)[SD-Karte/CGeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:72,7 KB, free space: 100,1 GB, files on device: 0)
  - GPX: SD-Karte/CGeo/gpx (Default)[SD-Karte/CGeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fgpx, Av:true, files:10, dirs:0, totalFileSize:76,4 MB, free space: 100,1 GB, files on device: 0)
  - BACKUP: SD-Karte/CGeo/backup (Default)[SD-Karte/CGeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fbackup, Av:true, files:>=10, dirs:>=10, totalFileSize:>=253,8 MB, free space: 100,1 GB, files on device: 0)
  - FIELD_NOTES: SD-Karte/CGeo/field-notes (Default)[SD-Karte/CGeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Ffield-notes, Av:true, files:4, dirs:0, totalFileSize:8,4 KB, free space: 100,1 GB, files on device: 0)
  - SPOILER_IMAGES: SD-Karte/CGeo/GeocachePhotos (Default)[SD-Karte/CGeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2FGeocachePhotos, Av:true, files:>=2, dirs:>=37, totalFileSize:>=5,2 MB, free space: 100,1 GB, files on device: 0)
  - ROUTING_BASE: SD-Karte/CGeo/routing (Default)[SD-Karte/CGeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Frouting, Av:true, files:9, dirs:1, totalFileSize:340,3 MB, free space: 100,1 GB, files on device: 0)
  - ROUTING_TILES: SD-Karte/CGeo/routing/segments4 (Default)[SD-Karte/CGeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Frouting%2Fsegments4, Av:true, files:2, dirs:0, totalFileSize:340,2 MB, free space: 100,1 GB, files on device: 0)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 68,0 GB, files on device: -1)
- Map render theme path: Elevate.zip:Elevate.xml
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo (1. Apr., 19:00):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:99,2 MB) on system internal storage

--- End of system information ---
```

### Additional Information

Screenshot_20221118-141453_cgeo

Generated waypoints are shown on the map, if they were "really" created and not only temporary for the map

### PR DESCRIPTION
**Pull request by murggel**
## Description

Remove the restriction on showing only caches with valid coordinates on the map.
Now caches with valid coordinates or having at least one waypoint with valid coordinates are shown.
So generated waypoints are shown on the map (their cache doesn't have a coordinate)

## Related issues

fix #13683

## Additional context

Implementing  a function to the map to display multiple waypoints as mentioned from @eddiemuc  in https://github.com/cgeo/cgeo/issues/13683#issuecomment-1321104426 was not necessary IMHO, since that implementation is already contained in displaying a single cache. 
So that means a more complex refactoring of displaying only waypoints on the map....

So for displaying a single waypoint there is already a cache for that purpose, which contains the waypoint.

### CODE REVIEW

File: main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java [hunk 1]
```diff
@@ -418,22 +416,34 @@ private void reloadCachesAndWaypoints() {
...
-                            onReceiveTargetUpdate(new AbstractDialogFragment.TargetInfo(cache.getCoords(), cache.getGeocode()));
+                    } else { // geocache mode: display ONLY geocache and its waypoints, if coordinates are available
+                        final Geopoint cacheCoordinates = cache.getCoords();
+                        final Waypoint firstWaypoint = cacheCoordinates == null ? cache.getFirstMatchingWaypoint(wp -> wp.getCoords() != null) : null;
+                        final Geopoint currentCoordinates = null != firstWaypoint ? firstWaypoint.getCoords() : cacheCoordinates;
+
+                        if (null != currentCoordinates) {
+                            viewModel.caches.write(false, c -> {
+                                c.clear();
+                                c.add(cache);
```
Comment (eddiemuc) [inline main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java]: This means there could be a cache here which has no coordinates. Doesn't this cause any problemss later? 
Does is make sense NOT to add the cache if it's coordinates are null?

**Comment by eddiemuc** [comment]
Clever idea! I have one small question though (see review comment)

File: main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java (hunk 1 above)
Comment (murggel) [reply main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java]: Good point...
checked usages:
* getClosestDistanceInM is used on the caches, but it checks for null-coordinates
* is used to create markers and distance-circles with GeoPrimitive.createMarker and GeoPrimitive.createCircles-> no null-check, null added to a list, also the other GeoPrimitives uses a Geopoint without null-check.

Will check those scenarios in emulator with the current implementation.
Will check same scenarios in emulator with not added a cache without coordinates.

Comment (murggel) [reply main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java]: Tested with both variants, no obviously wrong behaviour, but more secure with only caches having coordinates

**Comment by eddiemuc** [comment]
Lgtm
