### PR TITLE
Sort by 'Distance to target' for ADDRESS / COORDS searches

### LINKED ISSUE #11422: sort result of adress-search by distance to destination
### Tell us your idea!

For vacation I was looking for caches near our location. So I did a search for address. But the first caches which appears in the list were "far away" from the destination.

I guess it is because there are 400 cached loaded, sorted by distance to home / current location and not sorted by distance to destination location. 

### What solution would you suggest?

Sort the seatch-result for address by distance to destination location

### Is there an alternative?

Add max distance to search for adress to restrict result to an specific area

Or

Prefill filter with coordinates so the distance range can be easily adapted - not sure if that makes sense and would be helpful

### Additional Information

_No response_

### LINKED ISSUE #11666: nearby search from cache returns caches around current position
### Describe your problem!

From support ticket (and verified in a quick test): Doing a nearby search from cache detail page returns caches around your current position instead of caches around the cache's position.	

### How to reproduce?

- open a cache which is not close to your current position
- open menu => extra => "Caches im Umkreis"	

### Actual result after these steps?

c:geo will show you a list of caches around your current position (wrong value put into the filter)

### Expected result after these steps?

Show caches around the cache's position

### Reproducible

Yes

### c:geo Version

2021.09.08

### System information

_No response_

### Additional Information

ticket 237974

### PR DESCRIPTION
**Pull request by fm-sys**
fix #11666 / fix #11422

### CODE REVIEW

File: main/src/cgeo/geocaching/sorting/TargetDistanceComparator.java [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+import cgeo.geocaching.location.Geopoint;
+
+/**
+ * sorts caches by distance to given target position
+ *
+ */
+public class TargetDistanceComparator extends AbstractDistanceComparator {
+
+    public static final TargetDistanceComparator DISTANCE_TO_TARGET = new TargetDistanceComparator();
```
Comment (eddiemuc) [inline main/src/cgeo/geocaching/sorting/TargetDistanceComparator.java:11]: A construct using a static member is not necessary for target distance connector and should be removed. 

I assume this was copied from the approach for distance to current position. This is used to update the distance sort when the user moves and thus distance to caches may change.

For target distance however, the target coord and distance will remain constant, thus the target const can simply be passed in constructor. Usage of an ugly global var is not necessary.

File: main/src/cgeo/geocaching/sorting/SortActionProvider.java [hunk 2]
```diff
@@ -99,6 +100,9 @@ private void register(@StringRes final int resourceId, final Class<? extends Cac
 
     private void registerComparators() {
         registry.clear();
+        if (distanceToTargetAvailable) {
+            register(R.string.caches_sort_distance_target, TargetDistanceComparator.class, () -> TargetDistanceComparator.DISTANCE_TO_TARGET);
```
Comment (eddiemuc) [inline main/src/cgeo/geocaching/sorting/SortActionProvider.java:104]: Don't use ugly global constant here, pass target coords in a constructor to `TargetDistanceComparator` instead.

The reason why this is different for distance to user is explained in my second comment.

File: main/src/cgeo/geocaching/sorting/TargetDistanceComparator.java (hunk 1 above)
Comment (fm-sys) [reply main/src/cgeo/geocaching/sorting/TargetDistanceComparator.java:11]: We however need an initialized instance here... I can rename both global vars to "INSTANCE", but this will not solve the general problem. Any idea?



grafik

Comment (fm-sys) [reply main/src/cgeo/geocaching/sorting/TargetDistanceComparator.java]: I've just renamed both to "INSTANCE" for consistency. That's exactly how it is done for all other comparators as well. But I'm open for suggestions how to archive it differently...

File: main/src/cgeo/geocaching/sorting/SortActionProvider.java [hunk 3]
```diff
@@ -171,4 +175,8 @@ public void setSelection(final CacheComparator selection) {
     public void setIsEventsOnly(final boolean isEventsOnly) {
         this.isEventsOnly = isEventsOnly;
     }
+
+    public void setDistanceToTargetAvailable(final boolean distanceToTargetAvailable) {
```
Comment (eddiemuc) [inline main/src/cgeo/geocaching/sorting/SortActionProvider.java:179]: Suggested solution: change this method as follows:
- Instead of passing a boolean, pass the actual target coordinate in this method and create a corresponding TargetDistanceComparator. 
- Store this as instance member instead of the boolean flag.
- replace checks for target availability with checks on whether the comparator is null
- use the comparator where needed

File: main/src/cgeo/geocaching/sorting/TargetDistanceComparator.java (hunk 1 above)
Comment (eddiemuc) [reply main/src/cgeo/geocaching/sorting/TargetDistanceComparator.java]: @fm-sys see my comment on another method for solution suggestion . Alternatively, create a new instance of the comparator here. For this to work, the target coord needs to get a member of the class (but I would personally prefer my other suggestion)

In all the cases where INSTANCE is used, the comparator is not parameterized, so usage of a constant instance is fine. TargetDistanceComparator however needs to be parameterized.

 "Distance to user" is special due to the ever-changing user-coord and thus necessity to resort (but on the other hand there can always be one user-coordinate globally at any point in time).

**Comment by fm-sys** [comment]
@eddiemuc OK, hope I correctly understood your suggestion. Implemented in cb66ebd. 

Oh, and thanks for your review, feedback is always helpful and welcome! 👍

File: main/src/cgeo/geocaching/ui/CacheListAdapter.java [hunk 4]
```diff
@@ -180,8 +183,11 @@ public CacheComparator getCacheComparator() {
         if (cacheComparator == null && series) {
             return NameComparator.INSTANCE;
         }
+        if (cacheComparator == null && targetCoords != null) {
+            return new TargetDistanceComparator(targetCoords);
+        }
         if (cacheComparator == null) {
-            return DistanceComparator.DISTANCE_TO_GLOBAL_GPS;
+            return DistanceComparator.INSTANCE;
```
Comment (eddiemuc) [inline main/src/cgeo/geocaching/ui/CacheListAdapter.java:190]: INSTANCE is the standard name used for singleton pattern, it is known to be used for classes where only one instance exists and is used.

 If class `DistanceComparator` is meant to be a Singleton class which is solely used for compare to global GPS then I suggest renaming it to e.g. `GlobalGPSDistanceConparator`

If class `DistanceComparator` should also be used for other cases (like it was implemented before) then I would strongly suggest leaving the constant name as it was - the class is not a Singleton in this case.

Comment (fm-sys) [reply main/src/cgeo/geocaching/ui/CacheListAdapter.java:190]: > If class `DistanceComparator` is meant to be a Singleton class which is solely used for compare to global GPS then I suggest renaming it to e.g. `GlobalGPSDistanceConparator`

Yes, it is designed as singleton class, as userGPS will be the only value which can change. For other use cases we have `AbstractDistanceComparator` and `TargetDistanceComparator`. The comparator provider is BTW designed that way that every comparator requires it's own class, so every comparator class needs to be a singleton. I will rename the class accordingly.

Comment (fm-sys) [reply main/src/cgeo/geocaching/ui/CacheListAdapter.java:190]: My first implementation indeed was to create simply a new instance of DistanceComparator (without new classes), but it was not working without deeper refactoring...
